name: 'user-web'
port: 50000
user-srv:
  name: 'user-srv'
jwt:
  signing_key: '123456'
redis:
  host: '127.0.0.1'
  port: 6379
  password: ''
  db: 0
aliyun-sms:
  region_id: ''
  access_key_id: ''
  access_key_secret: ''
  sign_name: ''
  template_code: ''
  expire: 300
consul:
  host: '127.0.0.1'
  port: 18500
  address: '127.0.0.1'