// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: good.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Good_GoodList_FullMethodName             = "/Good/GoodList"
	Good_BatchGetGood_FullMethodName         = "/Good/BatchGetGood"
	Good_CreateGood_FullMethodName           = "/Good/CreateGood"
	Good_DeleteGood_FullMethodName           = "/Good/DeleteGood"
	Good_UpdateGood_FullMethodName           = "/Good/UpdateGood"
	Good_GetGoodDetail_FullMethodName        = "/Good/GetGoodDetail"
	Good_GetAllCategorysList_FullMethodName  = "/Good/GetAllCategorysList"
	Good_GetSubCategory_FullMethodName       = "/Good/GetSubCategory"
	Good_CreateCategory_FullMethodName       = "/Good/CreateCategory"
	Good_DeleteCategory_FullMethodName       = "/Good/DeleteCategory"
	Good_UpdateCategory_FullMethodName       = "/Good/UpdateCategory"
	Good_BrandList_FullMethodName            = "/Good/BrandList"
	Good_CreateBrand_FullMethodName          = "/Good/CreateBrand"
	Good_DeleteBrand_FullMethodName          = "/Good/DeleteBrand"
	Good_UpdateBrand_FullMethodName          = "/Good/UpdateBrand"
	Good_BannerList_FullMethodName           = "/Good/BannerList"
	Good_CreateBanner_FullMethodName         = "/Good/CreateBanner"
	Good_DeleteBanner_FullMethodName         = "/Good/DeleteBanner"
	Good_UpdateBanner_FullMethodName         = "/Good/UpdateBanner"
	Good_CategoryBrandList_FullMethodName    = "/Good/CategoryBrandList"
	Good_GetCategoryBrandList_FullMethodName = "/Good/GetCategoryBrandList"
	Good_CreateCategoryBrand_FullMethodName  = "/Good/CreateCategoryBrand"
	Good_DeleteCategoryBrand_FullMethodName  = "/Good/DeleteCategoryBrand"
	Good_UpdateCategoryBrand_FullMethodName  = "/Good/UpdateCategoryBrand"
)

// GoodClient is the client API for Good service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Good 服务定义
// 提供商品管理、分类管理、品牌管理、轮播图管理、品牌分类关联等功能的 gRPC 服务
type GoodClient interface {
	// 获取商品列表
	// 支持分页、筛选条件查询商品信息
	GoodList(ctx context.Context, in *GoodFilterRequest, opts ...grpc.CallOption) (*GoodListResponse, error)
	// 批量获取商品信息
	// 用于用户提交订单时批量查询多个商品的详细信息
	BatchGetGood(ctx context.Context, in *BatchGoodIdInfo, opts ...grpc.CallOption) (*GoodListResponse, error)
	// 创建商品
	// 添加新商品到系统中
	CreateGood(ctx context.Context, in *CreateGoodInfo, opts ...grpc.CallOption) (*GoodInfoResponse, error)
	// 删除商品
	// 根据商品 ID 删除指定商品
	DeleteGood(ctx context.Context, in *DeleteGoodInfo, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 更新商品
	// 修改已有商品的信息
	UpdateGood(ctx context.Context, in *CreateGoodInfo, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 获取商品详情
	// 查询单个商品的完整详细信息
	GetGoodDetail(ctx context.Context, in *GoodInfoRequest, opts ...grpc.CallOption) (*GoodInfoResponse, error)
	// 获取所有分类列表
	// 返回系统中所有商品分类的完整列表
	GetAllCategorysList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CategoryListResponse, error)
	// 获取子分类列表
	// 根据分类 ID 和层级获取该分类下的所有子分类
	GetSubCategory(ctx context.Context, in *CategoryListRequest, opts ...grpc.CallOption) (*SubCategoryListResponse, error)
	// 创建分类
	// 添加新的商品分类
	CreateCategory(ctx context.Context, in *CategoryInfoRequest, opts ...grpc.CallOption) (*CategoryInfoResponse, error)
	// 删除分类
	// 根据分类 ID 删除指定分类
	DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 更新分类
	// 修改已有分类的信息
	UpdateCategory(ctx context.Context, in *CategoryInfoRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 获取品牌列表
	// 支持分页查询品牌信息
	BrandList(ctx context.Context, in *BrandFilterRequest, opts ...grpc.CallOption) (*BrandListResponse, error)
	// 创建品牌
	// 添加新的品牌信息
	CreateBrand(ctx context.Context, in *BrandRequest, opts ...grpc.CallOption) (*BrandInfoResponse, error)
	// 删除品牌
	// 根据品牌 ID 删除指定品牌
	DeleteBrand(ctx context.Context, in *BrandRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 更新品牌
	// 修改已有品牌的信息
	UpdateBrand(ctx context.Context, in *BrandRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 获取轮播图列表
	// 返回所有轮播图信息
	BannerList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*BannerListResponse, error)
	// 创建轮播图
	// 添加新的轮播图
	CreateBanner(ctx context.Context, in *BannerRequest, opts ...grpc.CallOption) (*BannerResponse, error)
	// 删除轮播图
	// 根据轮播图 ID 删除指定轮播图
	DeleteBanner(ctx context.Context, in *BannerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 更新轮播图
	// 修改已有轮播图的信息
	UpdateBanner(ctx context.Context, in *BannerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 获取品牌分类关联列表
	// 支持分页查询品牌与分类的关联关系
	CategoryBrandList(ctx context.Context, in *CategoryBrandFilterRequest, opts ...grpc.CallOption) (*CategoryBrandListResponse, error)
	// 通过分类获取品牌列表
	// 根据分类 ID 查询该分类下的所有品牌
	GetCategoryBrandList(ctx context.Context, in *CategoryInfoRequest, opts ...grpc.CallOption) (*BrandListResponse, error)
	// 创建品牌分类关联
	// 建立品牌与分类之间的关联关系
	CreateCategoryBrand(ctx context.Context, in *CategoryBrandRequest, opts ...grpc.CallOption) (*CategoryBrandResponse, error)
	// 删除品牌分类关联
	// 删除品牌与分类之间的关联关系
	DeleteCategoryBrand(ctx context.Context, in *CategoryBrandRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 更新品牌分类关联
	// 修改品牌与分类之间的关联关系
	UpdateCategoryBrand(ctx context.Context, in *CategoryBrandRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type goodClient struct {
	cc grpc.ClientConnInterface
}

func NewGoodClient(cc grpc.ClientConnInterface) GoodClient {
	return &goodClient{cc}
}

func (c *goodClient) GoodList(ctx context.Context, in *GoodFilterRequest, opts ...grpc.CallOption) (*GoodListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GoodListResponse)
	err := c.cc.Invoke(ctx, Good_GoodList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodClient) BatchGetGood(ctx context.Context, in *BatchGoodIdInfo, opts ...grpc.CallOption) (*GoodListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GoodListResponse)
	err := c.cc.Invoke(ctx, Good_BatchGetGood_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodClient) CreateGood(ctx context.Context, in *CreateGoodInfo, opts ...grpc.CallOption) (*GoodInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GoodInfoResponse)
	err := c.cc.Invoke(ctx, Good_CreateGood_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodClient) DeleteGood(ctx context.Context, in *DeleteGoodInfo, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Good_DeleteGood_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodClient) UpdateGood(ctx context.Context, in *CreateGoodInfo, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Good_UpdateGood_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodClient) GetGoodDetail(ctx context.Context, in *GoodInfoRequest, opts ...grpc.CallOption) (*GoodInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GoodInfoResponse)
	err := c.cc.Invoke(ctx, Good_GetGoodDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodClient) GetAllCategorysList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CategoryListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CategoryListResponse)
	err := c.cc.Invoke(ctx, Good_GetAllCategorysList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodClient) GetSubCategory(ctx context.Context, in *CategoryListRequest, opts ...grpc.CallOption) (*SubCategoryListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubCategoryListResponse)
	err := c.cc.Invoke(ctx, Good_GetSubCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodClient) CreateCategory(ctx context.Context, in *CategoryInfoRequest, opts ...grpc.CallOption) (*CategoryInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CategoryInfoResponse)
	err := c.cc.Invoke(ctx, Good_CreateCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodClient) DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Good_DeleteCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodClient) UpdateCategory(ctx context.Context, in *CategoryInfoRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Good_UpdateCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodClient) BrandList(ctx context.Context, in *BrandFilterRequest, opts ...grpc.CallOption) (*BrandListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BrandListResponse)
	err := c.cc.Invoke(ctx, Good_BrandList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodClient) CreateBrand(ctx context.Context, in *BrandRequest, opts ...grpc.CallOption) (*BrandInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BrandInfoResponse)
	err := c.cc.Invoke(ctx, Good_CreateBrand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodClient) DeleteBrand(ctx context.Context, in *BrandRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Good_DeleteBrand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodClient) UpdateBrand(ctx context.Context, in *BrandRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Good_UpdateBrand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodClient) BannerList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*BannerListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BannerListResponse)
	err := c.cc.Invoke(ctx, Good_BannerList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodClient) CreateBanner(ctx context.Context, in *BannerRequest, opts ...grpc.CallOption) (*BannerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BannerResponse)
	err := c.cc.Invoke(ctx, Good_CreateBanner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodClient) DeleteBanner(ctx context.Context, in *BannerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Good_DeleteBanner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodClient) UpdateBanner(ctx context.Context, in *BannerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Good_UpdateBanner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodClient) CategoryBrandList(ctx context.Context, in *CategoryBrandFilterRequest, opts ...grpc.CallOption) (*CategoryBrandListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CategoryBrandListResponse)
	err := c.cc.Invoke(ctx, Good_CategoryBrandList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodClient) GetCategoryBrandList(ctx context.Context, in *CategoryInfoRequest, opts ...grpc.CallOption) (*BrandListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BrandListResponse)
	err := c.cc.Invoke(ctx, Good_GetCategoryBrandList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodClient) CreateCategoryBrand(ctx context.Context, in *CategoryBrandRequest, opts ...grpc.CallOption) (*CategoryBrandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CategoryBrandResponse)
	err := c.cc.Invoke(ctx, Good_CreateCategoryBrand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodClient) DeleteCategoryBrand(ctx context.Context, in *CategoryBrandRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Good_DeleteCategoryBrand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodClient) UpdateCategoryBrand(ctx context.Context, in *CategoryBrandRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Good_UpdateCategoryBrand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoodServer is the server API for Good service.
// All implementations must embed UnimplementedGoodServer
// for forward compatibility.
//
// Good 服务定义
// 提供商品管理、分类管理、品牌管理、轮播图管理、品牌分类关联等功能的 gRPC 服务
type GoodServer interface {
	// 获取商品列表
	// 支持分页、筛选条件查询商品信息
	GoodList(context.Context, *GoodFilterRequest) (*GoodListResponse, error)
	// 批量获取商品信息
	// 用于用户提交订单时批量查询多个商品的详细信息
	BatchGetGood(context.Context, *BatchGoodIdInfo) (*GoodListResponse, error)
	// 创建商品
	// 添加新商品到系统中
	CreateGood(context.Context, *CreateGoodInfo) (*GoodInfoResponse, error)
	// 删除商品
	// 根据商品 ID 删除指定商品
	DeleteGood(context.Context, *DeleteGoodInfo) (*emptypb.Empty, error)
	// 更新商品
	// 修改已有商品的信息
	UpdateGood(context.Context, *CreateGoodInfo) (*emptypb.Empty, error)
	// 获取商品详情
	// 查询单个商品的完整详细信息
	GetGoodDetail(context.Context, *GoodInfoRequest) (*GoodInfoResponse, error)
	// 获取所有分类列表
	// 返回系统中所有商品分类的完整列表
	GetAllCategorysList(context.Context, *emptypb.Empty) (*CategoryListResponse, error)
	// 获取子分类列表
	// 根据分类 ID 和层级获取该分类下的所有子分类
	GetSubCategory(context.Context, *CategoryListRequest) (*SubCategoryListResponse, error)
	// 创建分类
	// 添加新的商品分类
	CreateCategory(context.Context, *CategoryInfoRequest) (*CategoryInfoResponse, error)
	// 删除分类
	// 根据分类 ID 删除指定分类
	DeleteCategory(context.Context, *DeleteCategoryRequest) (*emptypb.Empty, error)
	// 更新分类
	// 修改已有分类的信息
	UpdateCategory(context.Context, *CategoryInfoRequest) (*emptypb.Empty, error)
	// 获取品牌列表
	// 支持分页查询品牌信息
	BrandList(context.Context, *BrandFilterRequest) (*BrandListResponse, error)
	// 创建品牌
	// 添加新的品牌信息
	CreateBrand(context.Context, *BrandRequest) (*BrandInfoResponse, error)
	// 删除品牌
	// 根据品牌 ID 删除指定品牌
	DeleteBrand(context.Context, *BrandRequest) (*emptypb.Empty, error)
	// 更新品牌
	// 修改已有品牌的信息
	UpdateBrand(context.Context, *BrandRequest) (*emptypb.Empty, error)
	// 获取轮播图列表
	// 返回所有轮播图信息
	BannerList(context.Context, *emptypb.Empty) (*BannerListResponse, error)
	// 创建轮播图
	// 添加新的轮播图
	CreateBanner(context.Context, *BannerRequest) (*BannerResponse, error)
	// 删除轮播图
	// 根据轮播图 ID 删除指定轮播图
	DeleteBanner(context.Context, *BannerRequest) (*emptypb.Empty, error)
	// 更新轮播图
	// 修改已有轮播图的信息
	UpdateBanner(context.Context, *BannerRequest) (*emptypb.Empty, error)
	// 获取品牌分类关联列表
	// 支持分页查询品牌与分类的关联关系
	CategoryBrandList(context.Context, *CategoryBrandFilterRequest) (*CategoryBrandListResponse, error)
	// 通过分类获取品牌列表
	// 根据分类 ID 查询该分类下的所有品牌
	GetCategoryBrandList(context.Context, *CategoryInfoRequest) (*BrandListResponse, error)
	// 创建品牌分类关联
	// 建立品牌与分类之间的关联关系
	CreateCategoryBrand(context.Context, *CategoryBrandRequest) (*CategoryBrandResponse, error)
	// 删除品牌分类关联
	// 删除品牌与分类之间的关联关系
	DeleteCategoryBrand(context.Context, *CategoryBrandRequest) (*emptypb.Empty, error)
	// 更新品牌分类关联
	// 修改品牌与分类之间的关联关系
	UpdateCategoryBrand(context.Context, *CategoryBrandRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedGoodServer()
}

// UnimplementedGoodServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGoodServer struct{}

func (UnimplementedGoodServer) GoodList(context.Context, *GoodFilterRequest) (*GoodListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GoodList not implemented")
}
func (UnimplementedGoodServer) BatchGetGood(context.Context, *BatchGoodIdInfo) (*GoodListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGetGood not implemented")
}
func (UnimplementedGoodServer) CreateGood(context.Context, *CreateGoodInfo) (*GoodInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGood not implemented")
}
func (UnimplementedGoodServer) DeleteGood(context.Context, *DeleteGoodInfo) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteGood not implemented")
}
func (UnimplementedGoodServer) UpdateGood(context.Context, *CreateGoodInfo) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGood not implemented")
}
func (UnimplementedGoodServer) GetGoodDetail(context.Context, *GoodInfoRequest) (*GoodInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGoodDetail not implemented")
}
func (UnimplementedGoodServer) GetAllCategorysList(context.Context, *emptypb.Empty) (*CategoryListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllCategorysList not implemented")
}
func (UnimplementedGoodServer) GetSubCategory(context.Context, *CategoryListRequest) (*SubCategoryListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSubCategory not implemented")
}
func (UnimplementedGoodServer) CreateCategory(context.Context, *CategoryInfoRequest) (*CategoryInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCategory not implemented")
}
func (UnimplementedGoodServer) DeleteCategory(context.Context, *DeleteCategoryRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCategory not implemented")
}
func (UnimplementedGoodServer) UpdateCategory(context.Context, *CategoryInfoRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCategory not implemented")
}
func (UnimplementedGoodServer) BrandList(context.Context, *BrandFilterRequest) (*BrandListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BrandList not implemented")
}
func (UnimplementedGoodServer) CreateBrand(context.Context, *BrandRequest) (*BrandInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBrand not implemented")
}
func (UnimplementedGoodServer) DeleteBrand(context.Context, *BrandRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBrand not implemented")
}
func (UnimplementedGoodServer) UpdateBrand(context.Context, *BrandRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBrand not implemented")
}
func (UnimplementedGoodServer) BannerList(context.Context, *emptypb.Empty) (*BannerListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BannerList not implemented")
}
func (UnimplementedGoodServer) CreateBanner(context.Context, *BannerRequest) (*BannerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBanner not implemented")
}
func (UnimplementedGoodServer) DeleteBanner(context.Context, *BannerRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBanner not implemented")
}
func (UnimplementedGoodServer) UpdateBanner(context.Context, *BannerRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBanner not implemented")
}
func (UnimplementedGoodServer) CategoryBrandList(context.Context, *CategoryBrandFilterRequest) (*CategoryBrandListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CategoryBrandList not implemented")
}
func (UnimplementedGoodServer) GetCategoryBrandList(context.Context, *CategoryInfoRequest) (*BrandListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCategoryBrandList not implemented")
}
func (UnimplementedGoodServer) CreateCategoryBrand(context.Context, *CategoryBrandRequest) (*CategoryBrandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCategoryBrand not implemented")
}
func (UnimplementedGoodServer) DeleteCategoryBrand(context.Context, *CategoryBrandRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCategoryBrand not implemented")
}
func (UnimplementedGoodServer) UpdateCategoryBrand(context.Context, *CategoryBrandRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCategoryBrand not implemented")
}
func (UnimplementedGoodServer) mustEmbedUnimplementedGoodServer() {}
func (UnimplementedGoodServer) testEmbeddedByValue()              {}

// UnsafeGoodServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoodServer will
// result in compilation errors.
type UnsafeGoodServer interface {
	mustEmbedUnimplementedGoodServer()
}

func RegisterGoodServer(s grpc.ServiceRegistrar, srv GoodServer) {
	// If the following call panics, it indicates UnimplementedGoodServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Good_ServiceDesc, srv)
}

func _Good_GoodList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoodFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodServer).GoodList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Good_GoodList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodServer).GoodList(ctx, req.(*GoodFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Good_BatchGetGood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGoodIdInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodServer).BatchGetGood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Good_BatchGetGood_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodServer).BatchGetGood(ctx, req.(*BatchGoodIdInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Good_CreateGood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGoodInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodServer).CreateGood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Good_CreateGood_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodServer).CreateGood(ctx, req.(*CreateGoodInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Good_DeleteGood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGoodInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodServer).DeleteGood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Good_DeleteGood_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodServer).DeleteGood(ctx, req.(*DeleteGoodInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Good_UpdateGood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGoodInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodServer).UpdateGood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Good_UpdateGood_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodServer).UpdateGood(ctx, req.(*CreateGoodInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Good_GetGoodDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoodInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodServer).GetGoodDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Good_GetGoodDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodServer).GetGoodDetail(ctx, req.(*GoodInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Good_GetAllCategorysList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodServer).GetAllCategorysList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Good_GetAllCategorysList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodServer).GetAllCategorysList(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Good_GetSubCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodServer).GetSubCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Good_GetSubCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodServer).GetSubCategory(ctx, req.(*CategoryListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Good_CreateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodServer).CreateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Good_CreateCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodServer).CreateCategory(ctx, req.(*CategoryInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Good_DeleteCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodServer).DeleteCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Good_DeleteCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodServer).DeleteCategory(ctx, req.(*DeleteCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Good_UpdateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodServer).UpdateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Good_UpdateCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodServer).UpdateCategory(ctx, req.(*CategoryInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Good_BrandList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrandFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodServer).BrandList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Good_BrandList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodServer).BrandList(ctx, req.(*BrandFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Good_CreateBrand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodServer).CreateBrand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Good_CreateBrand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodServer).CreateBrand(ctx, req.(*BrandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Good_DeleteBrand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodServer).DeleteBrand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Good_DeleteBrand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodServer).DeleteBrand(ctx, req.(*BrandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Good_UpdateBrand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodServer).UpdateBrand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Good_UpdateBrand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodServer).UpdateBrand(ctx, req.(*BrandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Good_BannerList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodServer).BannerList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Good_BannerList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodServer).BannerList(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Good_CreateBanner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BannerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodServer).CreateBanner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Good_CreateBanner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodServer).CreateBanner(ctx, req.(*BannerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Good_DeleteBanner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BannerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodServer).DeleteBanner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Good_DeleteBanner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodServer).DeleteBanner(ctx, req.(*BannerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Good_UpdateBanner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BannerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodServer).UpdateBanner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Good_UpdateBanner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodServer).UpdateBanner(ctx, req.(*BannerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Good_CategoryBrandList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryBrandFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodServer).CategoryBrandList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Good_CategoryBrandList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodServer).CategoryBrandList(ctx, req.(*CategoryBrandFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Good_GetCategoryBrandList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodServer).GetCategoryBrandList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Good_GetCategoryBrandList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodServer).GetCategoryBrandList(ctx, req.(*CategoryInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Good_CreateCategoryBrand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryBrandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodServer).CreateCategoryBrand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Good_CreateCategoryBrand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodServer).CreateCategoryBrand(ctx, req.(*CategoryBrandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Good_DeleteCategoryBrand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryBrandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodServer).DeleteCategoryBrand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Good_DeleteCategoryBrand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodServer).DeleteCategoryBrand(ctx, req.(*CategoryBrandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Good_UpdateCategoryBrand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryBrandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodServer).UpdateCategoryBrand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Good_UpdateCategoryBrand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodServer).UpdateCategoryBrand(ctx, req.(*CategoryBrandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Good_ServiceDesc is the grpc.ServiceDesc for Good service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Good_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Good",
	HandlerType: (*GoodServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GoodList",
			Handler:    _Good_GoodList_Handler,
		},
		{
			MethodName: "BatchGetGood",
			Handler:    _Good_BatchGetGood_Handler,
		},
		{
			MethodName: "CreateGood",
			Handler:    _Good_CreateGood_Handler,
		},
		{
			MethodName: "DeleteGood",
			Handler:    _Good_DeleteGood_Handler,
		},
		{
			MethodName: "UpdateGood",
			Handler:    _Good_UpdateGood_Handler,
		},
		{
			MethodName: "GetGoodDetail",
			Handler:    _Good_GetGoodDetail_Handler,
		},
		{
			MethodName: "GetAllCategorysList",
			Handler:    _Good_GetAllCategorysList_Handler,
		},
		{
			MethodName: "GetSubCategory",
			Handler:    _Good_GetSubCategory_Handler,
		},
		{
			MethodName: "CreateCategory",
			Handler:    _Good_CreateCategory_Handler,
		},
		{
			MethodName: "DeleteCategory",
			Handler:    _Good_DeleteCategory_Handler,
		},
		{
			MethodName: "UpdateCategory",
			Handler:    _Good_UpdateCategory_Handler,
		},
		{
			MethodName: "BrandList",
			Handler:    _Good_BrandList_Handler,
		},
		{
			MethodName: "CreateBrand",
			Handler:    _Good_CreateBrand_Handler,
		},
		{
			MethodName: "DeleteBrand",
			Handler:    _Good_DeleteBrand_Handler,
		},
		{
			MethodName: "UpdateBrand",
			Handler:    _Good_UpdateBrand_Handler,
		},
		{
			MethodName: "BannerList",
			Handler:    _Good_BannerList_Handler,
		},
		{
			MethodName: "CreateBanner",
			Handler:    _Good_CreateBanner_Handler,
		},
		{
			MethodName: "DeleteBanner",
			Handler:    _Good_DeleteBanner_Handler,
		},
		{
			MethodName: "UpdateBanner",
			Handler:    _Good_UpdateBanner_Handler,
		},
		{
			MethodName: "CategoryBrandList",
			Handler:    _Good_CategoryBrandList_Handler,
		},
		{
			MethodName: "GetCategoryBrandList",
			Handler:    _Good_GetCategoryBrandList_Handler,
		},
		{
			MethodName: "CreateCategoryBrand",
			Handler:    _Good_CreateCategoryBrand_Handler,
		},
		{
			MethodName: "DeleteCategoryBrand",
			Handler:    _Good_DeleteCategoryBrand_Handler,
		},
		{
			MethodName: "UpdateCategoryBrand",
			Handler:    _Good_UpdateCategoryBrand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "good.proto",
}
