// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: order.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 空消息定义，用于不需要请求参数或响应数据的 RPC 方法
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

// 用户信息
type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *UserInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 订单状态更新请求
type OrderStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`          // 订单ID
	OrderSn       string                 `protobuf:"bytes,2,opt,name=orderSn,proto3" json:"orderSn,omitempty"` // 订单编号
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`   // 订单状态（待支付、已支付、已发货、已完成、已取消等）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderStatus) Reset() {
	*x = OrderStatus{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatus) ProtoMessage() {}

func (x *OrderStatus) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatus.ProtoReflect.Descriptor instead.
func (*OrderStatus) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *OrderStatus) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderStatus) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *OrderStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// 购物车商品请求（添加/修改）
type CartItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                  // 购物车项ID（更新时必填，创建时为0）
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`          // 用户ID
	GoodsId       int32                  `protobuf:"varint,3,opt,name=goodsId,proto3" json:"goodsId,omitempty"`        // 商品ID
	GoodsName     string                 `protobuf:"bytes,4,opt,name=goodsName,proto3" json:"goodsName,omitempty"`     // 商品名称
	GoodsImage    string                 `protobuf:"bytes,5,opt,name=goodsImage,proto3" json:"goodsImage,omitempty"`   // 商品图片URL
	GoodsPrice    float32                `protobuf:"fixed32,6,opt,name=goodsPrice,proto3" json:"goodsPrice,omitempty"` // 商品价格
	Nums          int32                  `protobuf:"varint,7,opt,name=nums,proto3" json:"nums,omitempty"`              // 商品数量
	Checked       bool                   `protobuf:"varint,8,opt,name=checked,proto3" json:"checked,omitempty"`        // 是否选中（用于结算）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItemRequest) Reset() {
	*x = CartItemRequest{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItemRequest) ProtoMessage() {}

func (x *CartItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItemRequest.ProtoReflect.Descriptor instead.
func (*CartItemRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *CartItemRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CartItemRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CartItemRequest) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *CartItemRequest) GetGoodsName() string {
	if x != nil {
		return x.GoodsName
	}
	return ""
}

func (x *CartItemRequest) GetGoodsImage() string {
	if x != nil {
		return x.GoodsImage
	}
	return ""
}

func (x *CartItemRequest) GetGoodsPrice() float32 {
	if x != nil {
		return x.GoodsPrice
	}
	return 0
}

func (x *CartItemRequest) GetNums() int32 {
	if x != nil {
		return x.Nums
	}
	return 0
}

func (x *CartItemRequest) GetChecked() bool {
	if x != nil {
		return x.Checked
	}
	return false
}

// 订单创建/查询请求
type OrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`          // 订单ID（查询时使用）
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`  // 用户ID
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"` // 收货地址
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`       // 收货人姓名
	Mobile        string                 `protobuf:"bytes,5,opt,name=mobile,proto3" json:"mobile,omitempty"`   // 收货人手机号
	Post          string                 `protobuf:"bytes,6,opt,name=post,proto3" json:"post,omitempty"`       // 用户留言/备注
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderRequest) Reset() {
	*x = OrderRequest{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRequest) ProtoMessage() {}

func (x *OrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRequest.ProtoReflect.Descriptor instead.
func (*OrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *OrderRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *OrderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *OrderRequest) GetPost() string {
	if x != nil {
		return x.Post
	}
	return ""
}

// 订单信息响应
type OrderInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`          // 订单ID
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`  // 用户ID
	OrderSn       string                 `protobuf:"bytes,3,opt,name=orderSn,proto3" json:"orderSn,omitempty"` // 订单编号
	PayType       string                 `protobuf:"bytes,4,opt,name=payType,proto3" json:"payType,omitempty"` // 支付方式（支付宝、微信、余额等）
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`   // 订单状态
	Post          string                 `protobuf:"bytes,6,opt,name=post,proto3" json:"post,omitempty"`       // 用户留言
	Total         float32                `protobuf:"fixed32,7,opt,name=total,proto3" json:"total,omitempty"`   // 订单总金额
	Address       string                 `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"` // 收货地址
	Name          string                 `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`       // 收货人姓名
	Mobile        string                 `protobuf:"bytes,10,opt,name=mobile,proto3" json:"mobile,omitempty"`  // 收货人手机号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfoResponse) Reset() {
	*x = OrderInfoResponse{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfoResponse) ProtoMessage() {}

func (x *OrderInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfoResponse.ProtoReflect.Descriptor instead.
func (*OrderInfoResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *OrderInfoResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderInfoResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderInfoResponse) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *OrderInfoResponse) GetPayType() string {
	if x != nil {
		return x.PayType
	}
	return ""
}

func (x *OrderInfoResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderInfoResponse) GetPost() string {
	if x != nil {
		return x.Post
	}
	return ""
}

func (x *OrderInfoResponse) GetTotal() float32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *OrderInfoResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *OrderInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderInfoResponse) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

// 购物车商品信息响应
type ShopCartInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`           // 购物车项ID
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`   // 用户ID
	GoodsId       int32                  `protobuf:"varint,3,opt,name=goodsId,proto3" json:"goodsId,omitempty"` // 商品ID
	Nums          int32                  `protobuf:"varint,4,opt,name=nums,proto3" json:"nums,omitempty"`       // 商品数量
	Checked       bool                   `protobuf:"varint,5,opt,name=checked,proto3" json:"checked,omitempty"` // 是否选中
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopCartInfoResponse) Reset() {
	*x = ShopCartInfoResponse{}
	mi := &file_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopCartInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopCartInfoResponse) ProtoMessage() {}

func (x *ShopCartInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopCartInfoResponse.ProtoReflect.Descriptor instead.
func (*ShopCartInfoResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

func (x *ShopCartInfoResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ShopCartInfoResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ShopCartInfoResponse) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *ShopCartInfoResponse) GetNums() int32 {
	if x != nil {
		return x.Nums
	}
	return 0
}

func (x *ShopCartInfoResponse) GetChecked() bool {
	if x != nil {
		return x.Checked
	}
	return false
}

// 订单商品明细响应
type OrderItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                  // 订单项ID
	OrderId       int32                  `protobuf:"varint,2,opt,name=orderId,proto3" json:"orderId,omitempty"`        // 订单ID
	GoodsId       int32                  `protobuf:"varint,3,opt,name=goodsId,proto3" json:"goodsId,omitempty"`        // 商品ID
	GoodsName     string                 `protobuf:"bytes,4,opt,name=goodsName,proto3" json:"goodsName,omitempty"`     // 商品名称
	GoodsImage    string                 `protobuf:"bytes,5,opt,name=goodsImage,proto3" json:"goodsImage,omitempty"`   // 商品图片URL
	GoodsPrice    float32                `protobuf:"fixed32,6,opt,name=goodsPrice,proto3" json:"goodsPrice,omitempty"` // 商品单价
	Nums          int32                  `protobuf:"varint,7,opt,name=nums,proto3" json:"nums,omitempty"`              // 购买数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemResponse) Reset() {
	*x = OrderItemResponse{}
	mi := &file_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemResponse) ProtoMessage() {}

func (x *OrderItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemResponse.ProtoReflect.Descriptor instead.
func (*OrderItemResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{7}
}

func (x *OrderItemResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderItemResponse) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderItemResponse) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *OrderItemResponse) GetGoodsName() string {
	if x != nil {
		return x.GoodsName
	}
	return ""
}

func (x *OrderItemResponse) GetGoodsImage() string {
	if x != nil {
		return x.GoodsImage
	}
	return ""
}

func (x *OrderItemResponse) GetGoodsPrice() float32 {
	if x != nil {
		return x.GoodsPrice
	}
	return 0
}

func (x *OrderItemResponse) GetNums() int32 {
	if x != nil {
		return x.Nums
	}
	return 0
}

// 订单详情响应（包含订单基本信息和商品明细）
type OrderInfoDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderInfo     *OrderInfoResponse     `protobuf:"bytes,1,opt,name=orderInfo,proto3" json:"orderInfo,omitempty"` // 订单基本信息
	Goods         []*OrderItemResponse   `protobuf:"bytes,2,rep,name=goods,proto3" json:"goods,omitempty"`         // 订单商品明细列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfoDetailResponse) Reset() {
	*x = OrderInfoDetailResponse{}
	mi := &file_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfoDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfoDetailResponse) ProtoMessage() {}

func (x *OrderInfoDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfoDetailResponse.ProtoReflect.Descriptor instead.
func (*OrderInfoDetailResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8}
}

func (x *OrderInfoDetailResponse) GetOrderInfo() *OrderInfoResponse {
	if x != nil {
		return x.OrderInfo
	}
	return nil
}

func (x *OrderInfoDetailResponse) GetGoods() []*OrderItemResponse {
	if x != nil {
		return x.Goods
	}
	return nil
}

// 订单列表查询请求（支持分页）
type OrderFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`           // 用户ID（为0时查询所有订单，管理员权限）
	Pages         int32                  `protobuf:"varint,2,opt,name=pages,proto3" json:"pages,omitempty"`             // 页码（从1开始）
	PagePerNums   int32                  `protobuf:"varint,3,opt,name=pagePerNums,proto3" json:"pagePerNums,omitempty"` // 每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderFilterRequest) Reset() {
	*x = OrderFilterRequest{}
	mi := &file_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderFilterRequest) ProtoMessage() {}

func (x *OrderFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderFilterRequest.ProtoReflect.Descriptor instead.
func (*OrderFilterRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{9}
}

func (x *OrderFilterRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderFilterRequest) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *OrderFilterRequest) GetPagePerNums() int32 {
	if x != nil {
		return x.PagePerNums
	}
	return 0
}

// 订单列表响应
type OrderListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"` // 订单总数
	Data          []*OrderInfoResponse   `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`    // 订单列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderListResponse) Reset() {
	*x = OrderListResponse{}
	mi := &file_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListResponse) ProtoMessage() {}

func (x *OrderListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListResponse.ProtoReflect.Descriptor instead.
func (*OrderListResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{10}
}

func (x *OrderListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *OrderListResponse) GetData() []*OrderInfoResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

// 购物车列表响应
type CartItemListResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Total         int32                   `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"` // 购物车商品总数
	Data          []*ShopCartInfoResponse `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`    // 购物车商品列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItemListResponse) Reset() {
	*x = CartItemListResponse{}
	mi := &file_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItemListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItemListResponse) ProtoMessage() {}

func (x *CartItemListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItemListResponse.ProtoReflect.Descriptor instead.
func (*CartItemListResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{11}
}

func (x *CartItemListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CartItemListResponse) GetData() []*ShopCartInfoResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\"\a\n" +
	"\x05Empty\"\x1a\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"O\n" +
	"\vOrderStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\aorderSn\x18\x02 \x01(\tR\aorderSn\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\xdf\x01\n" +
	"\x0fCartItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\x12\x18\n" +
	"\agoodsId\x18\x03 \x01(\x05R\agoodsId\x12\x1c\n" +
	"\tgoodsName\x18\x04 \x01(\tR\tgoodsName\x12\x1e\n" +
	"\n" +
	"goodsImage\x18\x05 \x01(\tR\n" +
	"goodsImage\x12\x1e\n" +
	"\n" +
	"goodsPrice\x18\x06 \x01(\x02R\n" +
	"goodsPrice\x12\x12\n" +
	"\x04nums\x18\a \x01(\x05R\x04nums\x12\x18\n" +
	"\achecked\x18\b \x01(\bR\achecked\"\x90\x01\n" +
	"\fOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x16\n" +
	"\x06mobile\x18\x05 \x01(\tR\x06mobile\x12\x12\n" +
	"\x04post\x18\x06 \x01(\tR\x04post\"\xf7\x01\n" +
	"\x11OrderInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\x12\x18\n" +
	"\aorderSn\x18\x03 \x01(\tR\aorderSn\x12\x18\n" +
	"\apayType\x18\x04 \x01(\tR\apayType\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x12\n" +
	"\x04post\x18\x06 \x01(\tR\x04post\x12\x14\n" +
	"\x05total\x18\a \x01(\x02R\x05total\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\x12\x12\n" +
	"\x04name\x18\t \x01(\tR\x04name\x12\x16\n" +
	"\x06mobile\x18\n" +
	" \x01(\tR\x06mobile\"\x86\x01\n" +
	"\x14ShopCartInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\x12\x18\n" +
	"\agoodsId\x18\x03 \x01(\x05R\agoodsId\x12\x12\n" +
	"\x04nums\x18\x04 \x01(\x05R\x04nums\x12\x18\n" +
	"\achecked\x18\x05 \x01(\bR\achecked\"\xc9\x01\n" +
	"\x11OrderItemResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\aorderId\x18\x02 \x01(\x05R\aorderId\x12\x18\n" +
	"\agoodsId\x18\x03 \x01(\x05R\agoodsId\x12\x1c\n" +
	"\tgoodsName\x18\x04 \x01(\tR\tgoodsName\x12\x1e\n" +
	"\n" +
	"goodsImage\x18\x05 \x01(\tR\n" +
	"goodsImage\x12\x1e\n" +
	"\n" +
	"goodsPrice\x18\x06 \x01(\x02R\n" +
	"goodsPrice\x12\x12\n" +
	"\x04nums\x18\a \x01(\x05R\x04nums\"u\n" +
	"\x17OrderInfoDetailResponse\x120\n" +
	"\torderInfo\x18\x01 \x01(\v2\x12.OrderInfoResponseR\torderInfo\x12(\n" +
	"\x05goods\x18\x02 \x03(\v2\x12.OrderItemResponseR\x05goods\"d\n" +
	"\x12OrderFilterRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\x12\x14\n" +
	"\x05pages\x18\x02 \x01(\x05R\x05pages\x12 \n" +
	"\vpagePerNums\x18\x03 \x01(\x05R\vpagePerNums\"Q\n" +
	"\x11OrderListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12&\n" +
	"\x04data\x18\x02 \x03(\v2\x12.OrderInfoResponseR\x04data\"W\n" +
	"\x14CartItemListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12)\n" +
	"\x04data\x18\x02 \x03(\v2\x15.ShopCartInfoResponseR\x04data2\x92\x03\n" +
	"\x05Order\x120\n" +
	"\fCartItemList\x12\t.UserInfo\x1a\x15.CartItemListResponse\x129\n" +
	"\x0eCreateCartItem\x12\x10.CartItemRequest\x1a\x15.ShopCartInfoResponse\x12*\n" +
	"\x0eUpdateCartItem\x12\x10.CartItemRequest\x1a\x06.Empty\x12*\n" +
	"\x0eDeleteCartItem\x12\x10.CartItemRequest\x1a\x06.Empty\x12+\n" +
	"\x06Create\x12\r.OrderRequest\x1a\x12.OrderInfoResponse\x124\n" +
	"\tOrderList\x12\x13.OrderFilterRequest\x1a\x12.OrderListResponse\x126\n" +
	"\vOrderDetail\x12\r.OrderRequest\x1a\x18.OrderInfoDetailResponse\x12)\n" +
	"\x11UpdateOrderStatus\x12\f.OrderStatus\x1a\x06.EmptyB\tZ\a.;protob\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_order_proto_goTypes = []any{
	(*Empty)(nil),                   // 0: Empty
	(*UserInfo)(nil),                // 1: UserInfo
	(*OrderStatus)(nil),             // 2: OrderStatus
	(*CartItemRequest)(nil),         // 3: CartItemRequest
	(*OrderRequest)(nil),            // 4: OrderRequest
	(*OrderInfoResponse)(nil),       // 5: OrderInfoResponse
	(*ShopCartInfoResponse)(nil),    // 6: ShopCartInfoResponse
	(*OrderItemResponse)(nil),       // 7: OrderItemResponse
	(*OrderInfoDetailResponse)(nil), // 8: OrderInfoDetailResponse
	(*OrderFilterRequest)(nil),      // 9: OrderFilterRequest
	(*OrderListResponse)(nil),       // 10: OrderListResponse
	(*CartItemListResponse)(nil),    // 11: CartItemListResponse
}
var file_order_proto_depIdxs = []int32{
	5,  // 0: OrderInfoDetailResponse.orderInfo:type_name -> OrderInfoResponse
	7,  // 1: OrderInfoDetailResponse.goods:type_name -> OrderItemResponse
	5,  // 2: OrderListResponse.data:type_name -> OrderInfoResponse
	6,  // 3: CartItemListResponse.data:type_name -> ShopCartInfoResponse
	1,  // 4: Order.CartItemList:input_type -> UserInfo
	3,  // 5: Order.CreateCartItem:input_type -> CartItemRequest
	3,  // 6: Order.UpdateCartItem:input_type -> CartItemRequest
	3,  // 7: Order.DeleteCartItem:input_type -> CartItemRequest
	4,  // 8: Order.Create:input_type -> OrderRequest
	9,  // 9: Order.OrderList:input_type -> OrderFilterRequest
	4,  // 10: Order.OrderDetail:input_type -> OrderRequest
	2,  // 11: Order.UpdateOrderStatus:input_type -> OrderStatus
	11, // 12: Order.CartItemList:output_type -> CartItemListResponse
	6,  // 13: Order.CreateCartItem:output_type -> ShopCartInfoResponse
	0,  // 14: Order.UpdateCartItem:output_type -> Empty
	0,  // 15: Order.DeleteCartItem:output_type -> Empty
	5,  // 16: Order.Create:output_type -> OrderInfoResponse
	10, // 17: Order.OrderList:output_type -> OrderListResponse
	8,  // 18: Order.OrderDetail:output_type -> OrderInfoDetailResponse
	0,  // 19: Order.UpdateOrderStatus:output_type -> Empty
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
