// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: inventory.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 空消息定义，用于不需要请求参数或响应数据的 RPC 方法
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{0}
}

type GoodInvInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodId        int32                  `protobuf:"varint,1,opt,name=goodId,proto3" json:"goodId,omitempty"`
	Nums          int32                  `protobuf:"varint,2,opt,name=nums,proto3" json:"nums,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodInvInfo) Reset() {
	*x = GoodInvInfo{}
	mi := &file_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodInvInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodInvInfo) ProtoMessage() {}

func (x *GoodInvInfo) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodInvInfo.ProtoReflect.Descriptor instead.
func (*GoodInvInfo) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *GoodInvInfo) GetGoodId() int32 {
	if x != nil {
		return x.GoodId
	}
	return 0
}

func (x *GoodInvInfo) GetNums() int32 {
	if x != nil {
		return x.Nums
	}
	return 0
}

type SellInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodInfos     []*GoodInvInfo         `protobuf:"bytes,1,rep,name=goodInfos,proto3" json:"goodInfos,omitempty"` // 商品库存信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellInfo) Reset() {
	*x = SellInfo{}
	mi := &file_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellInfo) ProtoMessage() {}

func (x *SellInfo) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellInfo.ProtoReflect.Descriptor instead.
func (*SellInfo) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *SellInfo) GetGoodInfos() []*GoodInvInfo {
	if x != nil {
		return x.GoodInfos
	}
	return nil
}

var File_inventory_proto protoreflect.FileDescriptor

const file_inventory_proto_rawDesc = "" +
	"\n" +
	"\x0finventory.proto\"\a\n" +
	"\x05Empty\"9\n" +
	"\vGoodInvInfo\x12\x16\n" +
	"\x06goodId\x18\x01 \x01(\x05R\x06goodId\x12\x12\n" +
	"\x04nums\x18\x02 \x01(\x05R\x04nums\"6\n" +
	"\bSellInfo\x12*\n" +
	"\tgoodInfos\x18\x01 \x03(\v2\f.GoodInvInfoR\tgoodInfos2\x8c\x01\n" +
	"\tInventory\x12\x1e\n" +
	"\x06SetInv\x12\f.GoodInvInfo\x1a\x06.Empty\x12'\n" +
	"\tInvDetail\x12\f.GoodInvInfo\x1a\f.GoodInvInfo\x12\x19\n" +
	"\x04Sell\x12\t.SellInfo\x1a\x06.Empty\x12\x1b\n" +
	"\x06Reback\x12\t.SellInfo\x1a\x06.EmptyB\tZ\a.;protob\x06proto3"

var (
	file_inventory_proto_rawDescOnce sync.Once
	file_inventory_proto_rawDescData []byte
)

func file_inventory_proto_rawDescGZIP() []byte {
	file_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_proto_rawDesc), len(file_inventory_proto_rawDesc)))
	})
	return file_inventory_proto_rawDescData
}

var file_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_inventory_proto_goTypes = []any{
	(*Empty)(nil),       // 0: Empty
	(*GoodInvInfo)(nil), // 1: GoodInvInfo
	(*SellInfo)(nil),    // 2: SellInfo
}
var file_inventory_proto_depIdxs = []int32{
	1, // 0: SellInfo.goodInfos:type_name -> GoodInvInfo
	1, // 1: Inventory.SetInv:input_type -> GoodInvInfo
	1, // 2: Inventory.InvDetail:input_type -> GoodInvInfo
	2, // 3: Inventory.Sell:input_type -> SellInfo
	2, // 4: Inventory.Reback:input_type -> SellInfo
	0, // 5: Inventory.SetInv:output_type -> Empty
	1, // 6: Inventory.InvDetail:output_type -> GoodInvInfo
	0, // 7: Inventory.Sell:output_type -> Empty
	0, // 8: Inventory.Reback:output_type -> Empty
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_inventory_proto_init() }
func file_inventory_proto_init() {
	if File_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_proto_rawDesc), len(file_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_proto_depIdxs,
		MessageInfos:      file_inventory_proto_msgTypes,
	}.Build()
	File_inventory_proto = out.File
	file_inventory_proto_goTypes = nil
	file_inventory_proto_depIdxs = nil
}
