services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root123456
      - MYSQL_DATABASE=shop_user_srv
      - MYSQL_USER=shop_user
      - MYSQL_PASSWORD=shop123456
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - shop-network

  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - shop-network


volumes:
  mongo-data:
  mysql-data:
  redis-data:
  consul-data:
  nacos-data:
  nacos-logs:
