// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: good.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 空消息定义，用于不需要请求参数或响应数据的 RPC 方法
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_good_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{0}
}

// 分类列表请求
// 用于获取子分类时的请求参数
type CategoryListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分类 ID，0 表示获取根分类
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 分类层级，用于指定查询哪一层级的子分类
	Level         int32 `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryListRequest) Reset() {
	*x = CategoryListRequest{}
	mi := &file_good_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryListRequest) ProtoMessage() {}

func (x *CategoryListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryListRequest.ProtoReflect.Descriptor instead.
func (*CategoryListRequest) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{1}
}

func (x *CategoryListRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryListRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

// 分类信息请求
// 用于创建或更新分类时的请求参数
type CategoryInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分类 ID，创建时为空，更新时必填
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 分类名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 父分类 ID，顶级分类为 0
	ParentCategory int32 `protobuf:"varint,3,opt,name=parentCategory,proto3" json:"parentCategory,omitempty"`
	// 分类层级，1=一级分类，2=二级分类，3=三级分类
	Level int32 `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	// 是否在导航栏显示
	IsTab         bool `protobuf:"varint,5,opt,name=isTab,proto3" json:"isTab,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryInfoRequest) Reset() {
	*x = CategoryInfoRequest{}
	mi := &file_good_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryInfoRequest) ProtoMessage() {}

func (x *CategoryInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryInfoRequest.ProtoReflect.Descriptor instead.
func (*CategoryInfoRequest) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{2}
}

func (x *CategoryInfoRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryInfoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryInfoRequest) GetParentCategory() int32 {
	if x != nil {
		return x.ParentCategory
	}
	return 0
}

func (x *CategoryInfoRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CategoryInfoRequest) GetIsTab() bool {
	if x != nil {
		return x.IsTab
	}
	return false
}

// 删除分类请求
type DeleteCategoryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 要删除的分类 ID
	Id            int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCategoryRequest) Reset() {
	*x = DeleteCategoryRequest{}
	mi := &file_good_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCategoryRequest) ProtoMessage() {}

func (x *DeleteCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCategoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteCategoryRequest) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteCategoryRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 查询分类请求
// 用于根据条件查询分类
type QueryCategoryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分类 ID
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 分类名称（支持模糊查询）
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCategoryRequest) Reset() {
	*x = QueryCategoryRequest{}
	mi := &file_good_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCategoryRequest) ProtoMessage() {}

func (x *QueryCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCategoryRequest.ProtoReflect.Descriptor instead.
func (*QueryCategoryRequest) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{4}
}

func (x *QueryCategoryRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *QueryCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 分类信息响应
// 返回单个分类的完整信息
type CategoryInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分类 ID
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 分类名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 父分类 ID
	ParentCategory int32 `protobuf:"varint,3,opt,name=parentCategory,proto3" json:"parentCategory,omitempty"`
	// 分类层级
	Level int32 `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	// 是否在导航栏显示
	IsTab         bool `protobuf:"varint,5,opt,name=isTab,proto3" json:"isTab,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryInfoResponse) Reset() {
	*x = CategoryInfoResponse{}
	mi := &file_good_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryInfoResponse) ProtoMessage() {}

func (x *CategoryInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryInfoResponse.ProtoReflect.Descriptor instead.
func (*CategoryInfoResponse) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{5}
}

func (x *CategoryInfoResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryInfoResponse) GetParentCategory() int32 {
	if x != nil {
		return x.ParentCategory
	}
	return 0
}

func (x *CategoryInfoResponse) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CategoryInfoResponse) GetIsTab() bool {
	if x != nil {
		return x.IsTab
	}
	return false
}

// 分类列表响应
// 返回多个分类的分页列表
type CategoryListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 总记录数
	Total int32 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// 分类数据列表
	Data []*CategoryInfoResponse `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	// JSON 格式的额外数据（用于前端展示）
	JsonData      string `protobuf:"bytes,3,opt,name=jsonData,proto3" json:"jsonData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryListResponse) Reset() {
	*x = CategoryListResponse{}
	mi := &file_good_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryListResponse) ProtoMessage() {}

func (x *CategoryListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryListResponse.ProtoReflect.Descriptor instead.
func (*CategoryListResponse) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{6}
}

func (x *CategoryListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CategoryListResponse) GetData() []*CategoryInfoResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CategoryListResponse) GetJsonData() string {
	if x != nil {
		return x.JsonData
	}
	return ""
}

// 子分类列表响应
// 返回某个分类及其子分类的完整信息
type SubCategoryListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 总记录数
	Total int32 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// 当前分类信息
	Info *CategoryInfoResponse `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	// 子分类列表
	SubCategorys  []*CategoryInfoResponse `protobuf:"bytes,3,rep,name=subCategorys,proto3" json:"subCategorys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubCategoryListResponse) Reset() {
	*x = SubCategoryListResponse{}
	mi := &file_good_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubCategoryListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubCategoryListResponse) ProtoMessage() {}

func (x *SubCategoryListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubCategoryListResponse.ProtoReflect.Descriptor instead.
func (*SubCategoryListResponse) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{7}
}

func (x *SubCategoryListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SubCategoryListResponse) GetInfo() *CategoryInfoResponse {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *SubCategoryListResponse) GetSubCategorys() []*CategoryInfoResponse {
	if x != nil {
		return x.SubCategorys
	}
	return nil
}

// 品牌分类关联筛选请求
// 用于分页查询品牌分类关联关系
type CategoryBrandFilterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 当前页码，从 1 开始
	Pages int32 `protobuf:"varint,1,opt,name=pages,proto3" json:"pages,omitempty"`
	// 每页记录数
	PagePerNums   int32 `protobuf:"varint,2,opt,name=pagePerNums,proto3" json:"pagePerNums,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryBrandFilterRequest) Reset() {
	*x = CategoryBrandFilterRequest{}
	mi := &file_good_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryBrandFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryBrandFilterRequest) ProtoMessage() {}

func (x *CategoryBrandFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryBrandFilterRequest.ProtoReflect.Descriptor instead.
func (*CategoryBrandFilterRequest) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{8}
}

func (x *CategoryBrandFilterRequest) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *CategoryBrandFilterRequest) GetPagePerNums() int32 {
	if x != nil {
		return x.PagePerNums
	}
	return 0
}

// 通用筛选请求
// 用于基础的分页查询
type FilterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 当前页码，从 1 开始
	Pages int32 `protobuf:"varint,1,opt,name=pages,proto3" json:"pages,omitempty"`
	// 每页记录数
	PagePerNums   int32 `protobuf:"varint,2,opt,name=pagePerNums,proto3" json:"pagePerNums,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterRequest) Reset() {
	*x = FilterRequest{}
	mi := &file_good_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterRequest) ProtoMessage() {}

func (x *FilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterRequest.ProtoReflect.Descriptor instead.
func (*FilterRequest) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{9}
}

func (x *FilterRequest) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *FilterRequest) GetPagePerNums() int32 {
	if x != nil {
		return x.PagePerNums
	}
	return 0
}

// 品牌分类关联请求
// 用于创建或更新品牌分类关联
type CategoryBrandRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 关联记录 ID，创建时为空，更新时必填
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 分类 ID
	CategoryId int32 `protobuf:"varint,2,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	// 品牌 ID
	BrandId       int32 `protobuf:"varint,3,opt,name=brandId,proto3" json:"brandId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryBrandRequest) Reset() {
	*x = CategoryBrandRequest{}
	mi := &file_good_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryBrandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryBrandRequest) ProtoMessage() {}

func (x *CategoryBrandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryBrandRequest.ProtoReflect.Descriptor instead.
func (*CategoryBrandRequest) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{10}
}

func (x *CategoryBrandRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryBrandRequest) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CategoryBrandRequest) GetBrandId() int32 {
	if x != nil {
		return x.BrandId
	}
	return 0
}

// 品牌分类关联响应
// 返回品牌分类关联的完整信息
type CategoryBrandResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 关联记录 ID
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 品牌信息
	Brand *BrandInfoResponse `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	// 分类信息
	Category      *CategoryInfoResponse `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryBrandResponse) Reset() {
	*x = CategoryBrandResponse{}
	mi := &file_good_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryBrandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryBrandResponse) ProtoMessage() {}

func (x *CategoryBrandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryBrandResponse.ProtoReflect.Descriptor instead.
func (*CategoryBrandResponse) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{11}
}

func (x *CategoryBrandResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryBrandResponse) GetBrand() *BrandInfoResponse {
	if x != nil {
		return x.Brand
	}
	return nil
}

func (x *CategoryBrandResponse) GetCategory() *CategoryInfoResponse {
	if x != nil {
		return x.Category
	}
	return nil
}

// 轮播图请求
// 用于创建或更新轮播图
type BannerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 轮播图 ID，创建时为空，更新时必填
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 轮播图排序索引，数值越小排序越靠前
	Index int32 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	// 轮播图图片 URL
	Image string `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	// 轮播图跳转链接
	Url           string `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BannerRequest) Reset() {
	*x = BannerRequest{}
	mi := &file_good_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerRequest) ProtoMessage() {}

func (x *BannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerRequest.ProtoReflect.Descriptor instead.
func (*BannerRequest) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{12}
}

func (x *BannerRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BannerRequest) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *BannerRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *BannerRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// 轮播图响应
// 返回轮播图的完整信息
type BannerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 轮播图 ID
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 轮播图排序索引
	Index int32 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	// 轮播图图片 URL
	Image string `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	// 轮播图跳转链接
	Url           string `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BannerResponse) Reset() {
	*x = BannerResponse{}
	mi := &file_good_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BannerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerResponse) ProtoMessage() {}

func (x *BannerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerResponse.ProtoReflect.Descriptor instead.
func (*BannerResponse) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{13}
}

func (x *BannerResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BannerResponse) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *BannerResponse) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *BannerResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// 品牌筛选请求
// 用于分页查询品牌列表
type BrandFilterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 当前页码，从 1 开始
	Pages int32 `protobuf:"varint,1,opt,name=pages,proto3" json:"pages,omitempty"`
	// 每页记录数
	PagePerNums   int32 `protobuf:"varint,2,opt,name=pagePerNums,proto3" json:"pagePerNums,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrandFilterRequest) Reset() {
	*x = BrandFilterRequest{}
	mi := &file_good_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrandFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrandFilterRequest) ProtoMessage() {}

func (x *BrandFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrandFilterRequest.ProtoReflect.Descriptor instead.
func (*BrandFilterRequest) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{14}
}

func (x *BrandFilterRequest) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *BrandFilterRequest) GetPagePerNums() int32 {
	if x != nil {
		return x.PagePerNums
	}
	return 0
}

// 品牌请求
// 用于创建、更新、删除品牌
type BrandRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 品牌 ID，创建时为空，更新/删除时必填
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 品牌名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 品牌 Logo URL
	Logo          string `protobuf:"bytes,3,opt,name=logo,proto3" json:"logo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrandRequest) Reset() {
	*x = BrandRequest{}
	mi := &file_good_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrandRequest) ProtoMessage() {}

func (x *BrandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrandRequest.ProtoReflect.Descriptor instead.
func (*BrandRequest) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{15}
}

func (x *BrandRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BrandRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BrandRequest) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

// 品牌信息响应
// 返回品牌的完整信息
type BrandInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 品牌 ID
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 品牌名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 品牌 Logo URL
	Logo          string `protobuf:"bytes,3,opt,name=logo,proto3" json:"logo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrandInfoResponse) Reset() {
	*x = BrandInfoResponse{}
	mi := &file_good_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrandInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrandInfoResponse) ProtoMessage() {}

func (x *BrandInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrandInfoResponse.ProtoReflect.Descriptor instead.
func (*BrandInfoResponse) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{16}
}

func (x *BrandInfoResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BrandInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BrandInfoResponse) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

// 品牌列表响应
// 返回品牌的分页列表
type BrandListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 总记录数
	Total int32 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// 品牌数据列表
	Data          []*BrandInfoResponse `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrandListResponse) Reset() {
	*x = BrandListResponse{}
	mi := &file_good_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrandListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrandListResponse) ProtoMessage() {}

func (x *BrandListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrandListResponse.ProtoReflect.Descriptor instead.
func (*BrandListResponse) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{17}
}

func (x *BrandListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *BrandListResponse) GetData() []*BrandInfoResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

// 轮播图列表响应
// 返回轮播图的分页列表
type BannerListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 总记录数
	Total int32 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// 轮播图数据列表
	Data          []*BannerResponse `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BannerListResponse) Reset() {
	*x = BannerListResponse{}
	mi := &file_good_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BannerListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerListResponse) ProtoMessage() {}

func (x *BannerListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerListResponse.ProtoReflect.Descriptor instead.
func (*BannerListResponse) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{18}
}

func (x *BannerListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *BannerListResponse) GetData() []*BannerResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

// 品牌分类关联列表响应
// 返回品牌分类关联的分页列表
type CategoryBrandListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 总记录数
	Total int32 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// 品牌分类关联数据列表
	Data          []*CategoryBrandResponse `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryBrandListResponse) Reset() {
	*x = CategoryBrandListResponse{}
	mi := &file_good_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryBrandListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryBrandListResponse) ProtoMessage() {}

func (x *CategoryBrandListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryBrandListResponse.ProtoReflect.Descriptor instead.
func (*CategoryBrandListResponse) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{19}
}

func (x *CategoryBrandListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CategoryBrandListResponse) GetData() []*CategoryBrandResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

// 批量商品 ID 请求
// 用于批量查询商品信息
type BatchGoodIdInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 商品 ID 列表
	Id            []int32 `protobuf:"varint,1,rep,packed,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGoodIdInfo) Reset() {
	*x = BatchGoodIdInfo{}
	mi := &file_good_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGoodIdInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGoodIdInfo) ProtoMessage() {}

func (x *BatchGoodIdInfo) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGoodIdInfo.ProtoReflect.Descriptor instead.
func (*BatchGoodIdInfo) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{20}
}

func (x *BatchGoodIdInfo) GetId() []int32 {
	if x != nil {
		return x.Id
	}
	return nil
}

// 删除商品请求
type DeleteGoodInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 要删除的商品 ID
	Id            int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGoodInfo) Reset() {
	*x = DeleteGoodInfo{}
	mi := &file_good_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGoodInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGoodInfo) ProtoMessage() {}

func (x *DeleteGoodInfo) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGoodInfo.ProtoReflect.Descriptor instead.
func (*DeleteGoodInfo) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteGoodInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 分类简要信息响应
// 用于商品信息中嵌套返回分类的基本信息
type CategoryBriefInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分类 ID
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 分类名称
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryBriefInfoResponse) Reset() {
	*x = CategoryBriefInfoResponse{}
	mi := &file_good_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryBriefInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryBriefInfoResponse) ProtoMessage() {}

func (x *CategoryBriefInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryBriefInfoResponse.ProtoReflect.Descriptor instead.
func (*CategoryBriefInfoResponse) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{22}
}

func (x *CategoryBriefInfoResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryBriefInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 分类筛选请求
// 用于根据条件筛选分类
type CategoryFilterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分类 ID
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 是否在导航栏显示
	IsTab         bool `protobuf:"varint,2,opt,name=isTab,proto3" json:"isTab,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryFilterRequest) Reset() {
	*x = CategoryFilterRequest{}
	mi := &file_good_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryFilterRequest) ProtoMessage() {}

func (x *CategoryFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryFilterRequest.ProtoReflect.Descriptor instead.
func (*CategoryFilterRequest) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{23}
}

func (x *CategoryFilterRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryFilterRequest) GetIsTab() bool {
	if x != nil {
		return x.IsTab
	}
	return false
}

// 商品信息请求
// 用于查询单个商品详情
type GoodInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 商品 ID
	Id            int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodInfoRequest) Reset() {
	*x = GoodInfoRequest{}
	mi := &file_good_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodInfoRequest) ProtoMessage() {}

func (x *GoodInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodInfoRequest.ProtoReflect.Descriptor instead.
func (*GoodInfoRequest) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{24}
}

func (x *GoodInfoRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 创建商品信息
// 用于创建或更新商品时的请求参数
type CreateGoodInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 商品 ID，创建时为空，更新时必填
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 商品名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 商品货号（SKU）
	GoodSn string `protobuf:"bytes,3,opt,name=goodSn,proto3" json:"goodSn,omitempty"`
	// 商品库存数量
	Stocks int32 `protobuf:"varint,7,opt,name=stocks,proto3" json:"stocks,omitempty"`
	// 市场价格（原价）
	MarketPrice float32 `protobuf:"fixed32,8,opt,name=marketPrice,proto3" json:"marketPrice,omitempty"`
	// 店铺售价（实际售价）
	ShopPrice float32 `protobuf:"fixed32,9,opt,name=shopPrice,proto3" json:"shopPrice,omitempty"`
	// 商品简介
	GoodBrief string `protobuf:"bytes,10,opt,name=goodBrief,proto3" json:"goodBrief,omitempty"`
	// 商品详细描述（HTML 格式）
	GoodDesc string `protobuf:"bytes,11,opt,name=goodDesc,proto3" json:"goodDesc,omitempty"`
	// 是否包邮
	ShipFree bool `protobuf:"varint,12,opt,name=shipFree,proto3" json:"shipFree,omitempty"`
	// 商品图片 URL 列表
	Images []string `protobuf:"bytes,13,rep,name=images,proto3" json:"images,omitempty"`
	// 商品详情描述图片 URL 列表
	DescImages []string `protobuf:"bytes,14,rep,name=descImages,proto3" json:"descImages,omitempty"`
	// 商品封面图 URL
	GoodFrontImage string `protobuf:"bytes,15,opt,name=goodFrontImage,proto3" json:"goodFrontImage,omitempty"`
	// 是否新品
	IsNew bool `protobuf:"varint,16,opt,name=isNew,proto3" json:"isNew,omitempty"`
	// 是否热销
	IsHot bool `protobuf:"varint,17,opt,name=isHot,proto3" json:"isHot,omitempty"`
	// 是否上架销售
	OnSale bool `protobuf:"varint,18,opt,name=onSale,proto3" json:"onSale,omitempty"`
	// 所属分类 ID
	CategoryId int32 `protobuf:"varint,19,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	// 所属品牌 ID
	BrandId       int32 `protobuf:"varint,20,opt,name=brandId,proto3" json:"brandId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGoodInfo) Reset() {
	*x = CreateGoodInfo{}
	mi := &file_good_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGoodInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGoodInfo) ProtoMessage() {}

func (x *CreateGoodInfo) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGoodInfo.ProtoReflect.Descriptor instead.
func (*CreateGoodInfo) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{25}
}

func (x *CreateGoodInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateGoodInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGoodInfo) GetGoodSn() string {
	if x != nil {
		return x.GoodSn
	}
	return ""
}

func (x *CreateGoodInfo) GetStocks() int32 {
	if x != nil {
		return x.Stocks
	}
	return 0
}

func (x *CreateGoodInfo) GetMarketPrice() float32 {
	if x != nil {
		return x.MarketPrice
	}
	return 0
}

func (x *CreateGoodInfo) GetShopPrice() float32 {
	if x != nil {
		return x.ShopPrice
	}
	return 0
}

func (x *CreateGoodInfo) GetGoodBrief() string {
	if x != nil {
		return x.GoodBrief
	}
	return ""
}

func (x *CreateGoodInfo) GetGoodDesc() string {
	if x != nil {
		return x.GoodDesc
	}
	return ""
}

func (x *CreateGoodInfo) GetShipFree() bool {
	if x != nil {
		return x.ShipFree
	}
	return false
}

func (x *CreateGoodInfo) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *CreateGoodInfo) GetDescImages() []string {
	if x != nil {
		return x.DescImages
	}
	return nil
}

func (x *CreateGoodInfo) GetGoodFrontImage() string {
	if x != nil {
		return x.GoodFrontImage
	}
	return ""
}

func (x *CreateGoodInfo) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

func (x *CreateGoodInfo) GetIsHot() bool {
	if x != nil {
		return x.IsHot
	}
	return false
}

func (x *CreateGoodInfo) GetOnSale() bool {
	if x != nil {
		return x.OnSale
	}
	return false
}

func (x *CreateGoodInfo) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreateGoodInfo) GetBrandId() int32 {
	if x != nil {
		return x.BrandId
	}
	return 0
}

// 商品库存扣减请求
// 用于订单创建时扣减商品库存
type GoodReduceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 商品 ID
	GoodId int32 `protobuf:"varint,1,opt,name=GoodId,proto3" json:"GoodId,omitempty"`
	// 扣减数量
	Nums          int32 `protobuf:"varint,2,opt,name=nums,proto3" json:"nums,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodReduceRequest) Reset() {
	*x = GoodReduceRequest{}
	mi := &file_good_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodReduceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodReduceRequest) ProtoMessage() {}

func (x *GoodReduceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodReduceRequest.ProtoReflect.Descriptor instead.
func (*GoodReduceRequest) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{26}
}

func (x *GoodReduceRequest) GetGoodId() int32 {
	if x != nil {
		return x.GoodId
	}
	return 0
}

func (x *GoodReduceRequest) GetNums() int32 {
	if x != nil {
		return x.Nums
	}
	return 0
}

// 批量分类信息请求
// 用于批量查询分类信息
type BatchCategoryInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分类 ID 列表
	Id []int32 `protobuf:"varint,1,rep,packed,name=id,proto3" json:"id,omitempty"`
	// 商品数量限制
	GoodNums int32 `protobuf:"varint,2,opt,name=goodNums,proto3" json:"goodNums,omitempty"`
	// 品牌数量限制
	BrandNums     int32 `protobuf:"varint,3,opt,name=brandNums,proto3" json:"brandNums,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCategoryInfoRequest) Reset() {
	*x = BatchCategoryInfoRequest{}
	mi := &file_good_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCategoryInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCategoryInfoRequest) ProtoMessage() {}

func (x *BatchCategoryInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCategoryInfoRequest.ProtoReflect.Descriptor instead.
func (*BatchCategoryInfoRequest) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{27}
}

func (x *BatchCategoryInfoRequest) GetId() []int32 {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *BatchCategoryInfoRequest) GetGoodNums() int32 {
	if x != nil {
		return x.GoodNums
	}
	return 0
}

func (x *BatchCategoryInfoRequest) GetBrandNums() int32 {
	if x != nil {
		return x.BrandNums
	}
	return 0
}

// 商品筛选请求
// 用于分页筛选查询商品列表
type GoodFilterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 最低价格（用于价格区间筛选）
	PriceMin int32 `protobuf:"varint,1,opt,name=priceMin,proto3" json:"priceMin,omitempty"`
	// 最高价格（用于价格区间筛选）
	PriceMax int32 `protobuf:"varint,2,opt,name=priceMax,proto3" json:"priceMax,omitempty"`
	// 是否筛选热销商品
	IsHot bool `protobuf:"varint,3,opt,name=isHot,proto3" json:"isHot,omitempty"`
	// 是否筛选新品
	IsNew bool `protobuf:"varint,4,opt,name=isNew,proto3" json:"isNew,omitempty"`
	// 是否在导航栏显示
	IsTab bool `protobuf:"varint,5,opt,name=isTab,proto3" json:"isTab,omitempty"`
	// 顶级分类 ID（用于按分类筛选）
	TopCategory int32 `protobuf:"varint,6,opt,name=topCategory,proto3" json:"topCategory,omitempty"`
	// 当前页码，从 1 开始
	Pages int32 `protobuf:"varint,7,opt,name=pages,proto3" json:"pages,omitempty"`
	// 每页记录数
	PagePerNums int32 `protobuf:"varint,8,opt,name=pagePerNums,proto3" json:"pagePerNums,omitempty"`
	// 关键词（用于商品名称模糊搜索）
	KeyWords string `protobuf:"bytes,9,opt,name=keyWords,proto3" json:"keyWords,omitempty"`
	// 品牌 ID（用于按品牌筛选）
	Brand         int32 `protobuf:"varint,10,opt,name=brand,proto3" json:"brand,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodFilterRequest) Reset() {
	*x = GoodFilterRequest{}
	mi := &file_good_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodFilterRequest) ProtoMessage() {}

func (x *GoodFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodFilterRequest.ProtoReflect.Descriptor instead.
func (*GoodFilterRequest) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{28}
}

func (x *GoodFilterRequest) GetPriceMin() int32 {
	if x != nil {
		return x.PriceMin
	}
	return 0
}

func (x *GoodFilterRequest) GetPriceMax() int32 {
	if x != nil {
		return x.PriceMax
	}
	return 0
}

func (x *GoodFilterRequest) GetIsHot() bool {
	if x != nil {
		return x.IsHot
	}
	return false
}

func (x *GoodFilterRequest) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

func (x *GoodFilterRequest) GetIsTab() bool {
	if x != nil {
		return x.IsTab
	}
	return false
}

func (x *GoodFilterRequest) GetTopCategory() int32 {
	if x != nil {
		return x.TopCategory
	}
	return 0
}

func (x *GoodFilterRequest) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *GoodFilterRequest) GetPagePerNums() int32 {
	if x != nil {
		return x.PagePerNums
	}
	return 0
}

func (x *GoodFilterRequest) GetKeyWords() string {
	if x != nil {
		return x.KeyWords
	}
	return ""
}

func (x *GoodFilterRequest) GetBrand() int32 {
	if x != nil {
		return x.Brand
	}
	return 0
}

// 商品信息响应
// 返回商品的完整详细信息
type GoodInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 商品 ID
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 分类 ID
	CategoryId int32 `protobuf:"varint,2,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	// 商品名称
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// 商品货号（SKU）
	GoodSn string `protobuf:"bytes,4,opt,name=goodSn,proto3" json:"goodSn,omitempty"`
	// 点击次数/浏览量
	ClickNum int32 `protobuf:"varint,5,opt,name=clickNum,proto3" json:"clickNum,omitempty"`
	// 已售数量
	SoldNum int32 `protobuf:"varint,6,opt,name=soldNum,proto3" json:"soldNum,omitempty"`
	// 收藏数量
	FavNum int32 `protobuf:"varint,7,opt,name=favNum,proto3" json:"favNum,omitempty"`
	// 市场价格（原价）
	MarketPrice float32 `protobuf:"fixed32,9,opt,name=marketPrice,proto3" json:"marketPrice,omitempty"`
	// 店铺售价（实际售价）
	ShopPrice float32 `protobuf:"fixed32,10,opt,name=shopPrice,proto3" json:"shopPrice,omitempty"`
	// 商品简介
	GoodBrief string `protobuf:"bytes,11,opt,name=goodBrief,proto3" json:"goodBrief,omitempty"`
	// 商品详细描述
	GoodDesc string `protobuf:"bytes,12,opt,name=goodDesc,proto3" json:"goodDesc,omitempty"`
	// 是否包邮
	ShipFree bool `protobuf:"varint,13,opt,name=shipFree,proto3" json:"shipFree,omitempty"`
	// 商品图片 URL 列表
	Images []string `protobuf:"bytes,14,rep,name=images,proto3" json:"images,omitempty"`
	// 商品详情描述图片 URL 列表
	DescImages []string `protobuf:"bytes,15,rep,name=descImages,proto3" json:"descImages,omitempty"`
	// 商品封面图 URL
	GoodFrontImage string `protobuf:"bytes,16,opt,name=goodFrontImage,proto3" json:"goodFrontImage,omitempty"`
	// 是否新品
	IsNew bool `protobuf:"varint,17,opt,name=isNew,proto3" json:"isNew,omitempty"`
	// 是否热销
	IsHot bool `protobuf:"varint,18,opt,name=isHot,proto3" json:"isHot,omitempty"`
	// 是否上架销售
	OnSale bool `protobuf:"varint,19,opt,name=onSale,proto3" json:"onSale,omitempty"`
	// 添加时间（Unix 时间戳）
	AddTime int64 `protobuf:"varint,20,opt,name=addTime,proto3" json:"addTime,omitempty"`
	// 分类信息
	Category *CategoryBriefInfoResponse `protobuf:"bytes,21,opt,name=category,proto3" json:"category,omitempty"`
	// 品牌信息
	Brand         *BrandInfoResponse `protobuf:"bytes,22,opt,name=brand,proto3" json:"brand,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodInfoResponse) Reset() {
	*x = GoodInfoResponse{}
	mi := &file_good_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodInfoResponse) ProtoMessage() {}

func (x *GoodInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodInfoResponse.ProtoReflect.Descriptor instead.
func (*GoodInfoResponse) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{29}
}

func (x *GoodInfoResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GoodInfoResponse) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *GoodInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GoodInfoResponse) GetGoodSn() string {
	if x != nil {
		return x.GoodSn
	}
	return ""
}

func (x *GoodInfoResponse) GetClickNum() int32 {
	if x != nil {
		return x.ClickNum
	}
	return 0
}

func (x *GoodInfoResponse) GetSoldNum() int32 {
	if x != nil {
		return x.SoldNum
	}
	return 0
}

func (x *GoodInfoResponse) GetFavNum() int32 {
	if x != nil {
		return x.FavNum
	}
	return 0
}

func (x *GoodInfoResponse) GetMarketPrice() float32 {
	if x != nil {
		return x.MarketPrice
	}
	return 0
}

func (x *GoodInfoResponse) GetShopPrice() float32 {
	if x != nil {
		return x.ShopPrice
	}
	return 0
}

func (x *GoodInfoResponse) GetGoodBrief() string {
	if x != nil {
		return x.GoodBrief
	}
	return ""
}

func (x *GoodInfoResponse) GetGoodDesc() string {
	if x != nil {
		return x.GoodDesc
	}
	return ""
}

func (x *GoodInfoResponse) GetShipFree() bool {
	if x != nil {
		return x.ShipFree
	}
	return false
}

func (x *GoodInfoResponse) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *GoodInfoResponse) GetDescImages() []string {
	if x != nil {
		return x.DescImages
	}
	return nil
}

func (x *GoodInfoResponse) GetGoodFrontImage() string {
	if x != nil {
		return x.GoodFrontImage
	}
	return ""
}

func (x *GoodInfoResponse) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

func (x *GoodInfoResponse) GetIsHot() bool {
	if x != nil {
		return x.IsHot
	}
	return false
}

func (x *GoodInfoResponse) GetOnSale() bool {
	if x != nil {
		return x.OnSale
	}
	return false
}

func (x *GoodInfoResponse) GetAddTime() int64 {
	if x != nil {
		return x.AddTime
	}
	return 0
}

func (x *GoodInfoResponse) GetCategory() *CategoryBriefInfoResponse {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *GoodInfoResponse) GetBrand() *BrandInfoResponse {
	if x != nil {
		return x.Brand
	}
	return nil
}

// 商品列表响应
// 返回商品的分页列表
type GoodListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 总记录数
	Total int32 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// 商品数据列表
	Data          []*GoodInfoResponse `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodListResponse) Reset() {
	*x = GoodListResponse{}
	mi := &file_good_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodListResponse) ProtoMessage() {}

func (x *GoodListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodListResponse.ProtoReflect.Descriptor instead.
func (*GoodListResponse) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{30}
}

func (x *GoodListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GoodListResponse) GetData() []*GoodInfoResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_good_proto protoreflect.FileDescriptor

const file_good_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"good.proto\"\a\n" +
	"\x05Empty\";\n" +
	"\x13CategoryListRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\"\x8d\x01\n" +
	"\x13CategoryInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12&\n" +
	"\x0eparentCategory\x18\x03 \x01(\x05R\x0eparentCategory\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x14\n" +
	"\x05isTab\x18\x05 \x01(\bR\x05isTab\"'\n" +
	"\x15DeleteCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\":\n" +
	"\x14QueryCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x8e\x01\n" +
	"\x14CategoryInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12&\n" +
	"\x0eparentCategory\x18\x03 \x01(\x05R\x0eparentCategory\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x14\n" +
	"\x05isTab\x18\x05 \x01(\bR\x05isTab\"s\n" +
	"\x14CategoryListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12)\n" +
	"\x04data\x18\x02 \x03(\v2\x15.CategoryInfoResponseR\x04data\x12\x1a\n" +
	"\bjsonData\x18\x03 \x01(\tR\bjsonData\"\x95\x01\n" +
	"\x17SubCategoryListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12)\n" +
	"\x04info\x18\x02 \x01(\v2\x15.CategoryInfoResponseR\x04info\x129\n" +
	"\fsubCategorys\x18\x03 \x03(\v2\x15.CategoryInfoResponseR\fsubCategorys\"T\n" +
	"\x1aCategoryBrandFilterRequest\x12\x14\n" +
	"\x05pages\x18\x01 \x01(\x05R\x05pages\x12 \n" +
	"\vpagePerNums\x18\x02 \x01(\x05R\vpagePerNums\"G\n" +
	"\rFilterRequest\x12\x14\n" +
	"\x05pages\x18\x01 \x01(\x05R\x05pages\x12 \n" +
	"\vpagePerNums\x18\x02 \x01(\x05R\vpagePerNums\"`\n" +
	"\x14CategoryBrandRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x02 \x01(\x05R\n" +
	"categoryId\x12\x18\n" +
	"\abrandId\x18\x03 \x01(\x05R\abrandId\"\x84\x01\n" +
	"\x15CategoryBrandResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12(\n" +
	"\x05brand\x18\x02 \x01(\v2\x12.BrandInfoResponseR\x05brand\x121\n" +
	"\bcategory\x18\x03 \x01(\v2\x15.CategoryInfoResponseR\bcategory\"]\n" +
	"\rBannerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\"^\n" +
	"\x0eBannerResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\"L\n" +
	"\x12BrandFilterRequest\x12\x14\n" +
	"\x05pages\x18\x01 \x01(\x05R\x05pages\x12 \n" +
	"\vpagePerNums\x18\x02 \x01(\x05R\vpagePerNums\"F\n" +
	"\fBrandRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04logo\x18\x03 \x01(\tR\x04logo\"K\n" +
	"\x11BrandInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04logo\x18\x03 \x01(\tR\x04logo\"Q\n" +
	"\x11BrandListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12&\n" +
	"\x04data\x18\x02 \x03(\v2\x12.BrandInfoResponseR\x04data\"O\n" +
	"\x12BannerListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12#\n" +
	"\x04data\x18\x02 \x03(\v2\x0f.BannerResponseR\x04data\"]\n" +
	"\x19CategoryBrandListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12*\n" +
	"\x04data\x18\x02 \x03(\v2\x16.CategoryBrandResponseR\x04data\"!\n" +
	"\x0fBatchGoodIdInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x03(\x05R\x02id\" \n" +
	"\x0eDeleteGoodInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"?\n" +
	"\x19CategoryBriefInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"=\n" +
	"\x15CategoryFilterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05isTab\x18\x02 \x01(\bR\x05isTab\"!\n" +
	"\x0fGoodInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xd8\x03\n" +
	"\x0eCreateGoodInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06goodSn\x18\x03 \x01(\tR\x06goodSn\x12\x16\n" +
	"\x06stocks\x18\a \x01(\x05R\x06stocks\x12 \n" +
	"\vmarketPrice\x18\b \x01(\x02R\vmarketPrice\x12\x1c\n" +
	"\tshopPrice\x18\t \x01(\x02R\tshopPrice\x12\x1c\n" +
	"\tgoodBrief\x18\n" +
	" \x01(\tR\tgoodBrief\x12\x1a\n" +
	"\bgoodDesc\x18\v \x01(\tR\bgoodDesc\x12\x1a\n" +
	"\bshipFree\x18\f \x01(\bR\bshipFree\x12\x16\n" +
	"\x06images\x18\r \x03(\tR\x06images\x12\x1e\n" +
	"\n" +
	"descImages\x18\x0e \x03(\tR\n" +
	"descImages\x12&\n" +
	"\x0egoodFrontImage\x18\x0f \x01(\tR\x0egoodFrontImage\x12\x14\n" +
	"\x05isNew\x18\x10 \x01(\bR\x05isNew\x12\x14\n" +
	"\x05isHot\x18\x11 \x01(\bR\x05isHot\x12\x16\n" +
	"\x06onSale\x18\x12 \x01(\bR\x06onSale\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x13 \x01(\x05R\n" +
	"categoryId\x12\x18\n" +
	"\abrandId\x18\x14 \x01(\x05R\abrandId\"?\n" +
	"\x11GoodReduceRequest\x12\x16\n" +
	"\x06GoodId\x18\x01 \x01(\x05R\x06GoodId\x12\x12\n" +
	"\x04nums\x18\x02 \x01(\x05R\x04nums\"d\n" +
	"\x18BatchCategoryInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x03(\x05R\x02id\x12\x1a\n" +
	"\bgoodNums\x18\x02 \x01(\x05R\bgoodNums\x12\x1c\n" +
	"\tbrandNums\x18\x03 \x01(\x05R\tbrandNums\"\x99\x02\n" +
	"\x11GoodFilterRequest\x12\x1a\n" +
	"\bpriceMin\x18\x01 \x01(\x05R\bpriceMin\x12\x1a\n" +
	"\bpriceMax\x18\x02 \x01(\x05R\bpriceMax\x12\x14\n" +
	"\x05isHot\x18\x03 \x01(\bR\x05isHot\x12\x14\n" +
	"\x05isNew\x18\x04 \x01(\bR\x05isNew\x12\x14\n" +
	"\x05isTab\x18\x05 \x01(\bR\x05isTab\x12 \n" +
	"\vtopCategory\x18\x06 \x01(\x05R\vtopCategory\x12\x14\n" +
	"\x05pages\x18\a \x01(\x05R\x05pages\x12 \n" +
	"\vpagePerNums\x18\b \x01(\x05R\vpagePerNums\x12\x1a\n" +
	"\bkeyWords\x18\t \x01(\tR\bkeyWords\x12\x14\n" +
	"\x05brand\x18\n" +
	" \x01(\x05R\x05brand\"\xf2\x04\n" +
	"\x10GoodInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x02 \x01(\x05R\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06goodSn\x18\x04 \x01(\tR\x06goodSn\x12\x1a\n" +
	"\bclickNum\x18\x05 \x01(\x05R\bclickNum\x12\x18\n" +
	"\asoldNum\x18\x06 \x01(\x05R\asoldNum\x12\x16\n" +
	"\x06favNum\x18\a \x01(\x05R\x06favNum\x12 \n" +
	"\vmarketPrice\x18\t \x01(\x02R\vmarketPrice\x12\x1c\n" +
	"\tshopPrice\x18\n" +
	" \x01(\x02R\tshopPrice\x12\x1c\n" +
	"\tgoodBrief\x18\v \x01(\tR\tgoodBrief\x12\x1a\n" +
	"\bgoodDesc\x18\f \x01(\tR\bgoodDesc\x12\x1a\n" +
	"\bshipFree\x18\r \x01(\bR\bshipFree\x12\x16\n" +
	"\x06images\x18\x0e \x03(\tR\x06images\x12\x1e\n" +
	"\n" +
	"descImages\x18\x0f \x03(\tR\n" +
	"descImages\x12&\n" +
	"\x0egoodFrontImage\x18\x10 \x01(\tR\x0egoodFrontImage\x12\x14\n" +
	"\x05isNew\x18\x11 \x01(\bR\x05isNew\x12\x14\n" +
	"\x05isHot\x18\x12 \x01(\bR\x05isHot\x12\x16\n" +
	"\x06onSale\x18\x13 \x01(\bR\x06onSale\x12\x18\n" +
	"\aaddTime\x18\x14 \x01(\x03R\aaddTime\x126\n" +
	"\bcategory\x18\x15 \x01(\v2\x1a.CategoryBriefInfoResponseR\bcategory\x12(\n" +
	"\x05brand\x18\x16 \x01(\v2\x12.BrandInfoResponseR\x05brand\"O\n" +
	"\x10GoodListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12%\n" +
	"\x04data\x18\x02 \x03(\v2\x11.GoodInfoResponseR\x04data2\xdf\t\n" +
	"\x04Good\x121\n" +
	"\bGoodList\x12\x12.GoodFilterRequest\x1a\x11.GoodListResponse\x123\n" +
	"\fBatchGetGood\x12\x10.BatchGoodIdInfo\x1a\x11.GoodListResponse\x120\n" +
	"\n" +
	"CreateGood\x12\x0f.CreateGoodInfo\x1a\x11.GoodInfoResponse\x12%\n" +
	"\n" +
	"DeleteGood\x12\x0f.DeleteGoodInfo\x1a\x06.Empty\x12%\n" +
	"\n" +
	"UpdateGood\x12\x0f.CreateGoodInfo\x1a\x06.Empty\x124\n" +
	"\rGetGoodDetail\x12\x10.GoodInfoRequest\x1a\x11.GoodInfoResponse\x124\n" +
	"\x13GetAllCategorysList\x12\x06.Empty\x1a\x15.CategoryListResponse\x12@\n" +
	"\x0eGetSubCategory\x12\x14.CategoryListRequest\x1a\x18.SubCategoryListResponse\x12=\n" +
	"\x0eCreateCategory\x12\x14.CategoryInfoRequest\x1a\x15.CategoryInfoResponse\x120\n" +
	"\x0eDeleteCategory\x12\x16.DeleteCategoryRequest\x1a\x06.Empty\x12.\n" +
	"\x0eUpdateCategory\x12\x14.CategoryInfoRequest\x1a\x06.Empty\x124\n" +
	"\tBrandList\x12\x13.BrandFilterRequest\x1a\x12.BrandListResponse\x120\n" +
	"\vCreateBrand\x12\r.BrandRequest\x1a\x12.BrandInfoResponse\x12$\n" +
	"\vDeleteBrand\x12\r.BrandRequest\x1a\x06.Empty\x12$\n" +
	"\vUpdateBrand\x12\r.BrandRequest\x1a\x06.Empty\x12)\n" +
	"\n" +
	"BannerList\x12\x06.Empty\x1a\x13.BannerListResponse\x12/\n" +
	"\fCreateBanner\x12\x0e.BannerRequest\x1a\x0f.BannerResponse\x12&\n" +
	"\fDeleteBanner\x12\x0e.BannerRequest\x1a\x06.Empty\x12&\n" +
	"\fUpdateBanner\x12\x0e.BannerRequest\x1a\x06.Empty\x12L\n" +
	"\x11CategoryBrandList\x12\x1b.CategoryBrandFilterRequest\x1a\x1a.CategoryBrandListResponse\x12@\n" +
	"\x14GetCategoryBrandList\x12\x14.CategoryInfoRequest\x1a\x12.BrandListResponse\x12D\n" +
	"\x13CreateCategoryBrand\x12\x15.CategoryBrandRequest\x1a\x16.CategoryBrandResponse\x124\n" +
	"\x13DeleteCategoryBrand\x12\x15.CategoryBrandRequest\x1a\x06.Empty\x124\n" +
	"\x13UpdateCategoryBrand\x12\x15.CategoryBrandRequest\x1a\x06.EmptyB\tZ\a.;protob\x06proto3"

var (
	file_good_proto_rawDescOnce sync.Once
	file_good_proto_rawDescData []byte
)

func file_good_proto_rawDescGZIP() []byte {
	file_good_proto_rawDescOnce.Do(func() {
		file_good_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_good_proto_rawDesc), len(file_good_proto_rawDesc)))
	})
	return file_good_proto_rawDescData
}

var file_good_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_good_proto_goTypes = []any{
	(*Empty)(nil),                      // 0: Empty
	(*CategoryListRequest)(nil),        // 1: CategoryListRequest
	(*CategoryInfoRequest)(nil),        // 2: CategoryInfoRequest
	(*DeleteCategoryRequest)(nil),      // 3: DeleteCategoryRequest
	(*QueryCategoryRequest)(nil),       // 4: QueryCategoryRequest
	(*CategoryInfoResponse)(nil),       // 5: CategoryInfoResponse
	(*CategoryListResponse)(nil),       // 6: CategoryListResponse
	(*SubCategoryListResponse)(nil),    // 7: SubCategoryListResponse
	(*CategoryBrandFilterRequest)(nil), // 8: CategoryBrandFilterRequest
	(*FilterRequest)(nil),              // 9: FilterRequest
	(*CategoryBrandRequest)(nil),       // 10: CategoryBrandRequest
	(*CategoryBrandResponse)(nil),      // 11: CategoryBrandResponse
	(*BannerRequest)(nil),              // 12: BannerRequest
	(*BannerResponse)(nil),             // 13: BannerResponse
	(*BrandFilterRequest)(nil),         // 14: BrandFilterRequest
	(*BrandRequest)(nil),               // 15: BrandRequest
	(*BrandInfoResponse)(nil),          // 16: BrandInfoResponse
	(*BrandListResponse)(nil),          // 17: BrandListResponse
	(*BannerListResponse)(nil),         // 18: BannerListResponse
	(*CategoryBrandListResponse)(nil),  // 19: CategoryBrandListResponse
	(*BatchGoodIdInfo)(nil),            // 20: BatchGoodIdInfo
	(*DeleteGoodInfo)(nil),             // 21: DeleteGoodInfo
	(*CategoryBriefInfoResponse)(nil),  // 22: CategoryBriefInfoResponse
	(*CategoryFilterRequest)(nil),      // 23: CategoryFilterRequest
	(*GoodInfoRequest)(nil),            // 24: GoodInfoRequest
	(*CreateGoodInfo)(nil),             // 25: CreateGoodInfo
	(*GoodReduceRequest)(nil),          // 26: GoodReduceRequest
	(*BatchCategoryInfoRequest)(nil),   // 27: BatchCategoryInfoRequest
	(*GoodFilterRequest)(nil),          // 28: GoodFilterRequest
	(*GoodInfoResponse)(nil),           // 29: GoodInfoResponse
	(*GoodListResponse)(nil),           // 30: GoodListResponse
}
var file_good_proto_depIdxs = []int32{
	5,  // 0: CategoryListResponse.data:type_name -> CategoryInfoResponse
	5,  // 1: SubCategoryListResponse.info:type_name -> CategoryInfoResponse
	5,  // 2: SubCategoryListResponse.subCategorys:type_name -> CategoryInfoResponse
	16, // 3: CategoryBrandResponse.brand:type_name -> BrandInfoResponse
	5,  // 4: CategoryBrandResponse.category:type_name -> CategoryInfoResponse
	16, // 5: BrandListResponse.data:type_name -> BrandInfoResponse
	13, // 6: BannerListResponse.data:type_name -> BannerResponse
	11, // 7: CategoryBrandListResponse.data:type_name -> CategoryBrandResponse
	22, // 8: GoodInfoResponse.category:type_name -> CategoryBriefInfoResponse
	16, // 9: GoodInfoResponse.brand:type_name -> BrandInfoResponse
	29, // 10: GoodListResponse.data:type_name -> GoodInfoResponse
	28, // 11: Good.GoodList:input_type -> GoodFilterRequest
	20, // 12: Good.BatchGetGood:input_type -> BatchGoodIdInfo
	25, // 13: Good.CreateGood:input_type -> CreateGoodInfo
	21, // 14: Good.DeleteGood:input_type -> DeleteGoodInfo
	25, // 15: Good.UpdateGood:input_type -> CreateGoodInfo
	24, // 16: Good.GetGoodDetail:input_type -> GoodInfoRequest
	0,  // 17: Good.GetAllCategorysList:input_type -> Empty
	1,  // 18: Good.GetSubCategory:input_type -> CategoryListRequest
	2,  // 19: Good.CreateCategory:input_type -> CategoryInfoRequest
	3,  // 20: Good.DeleteCategory:input_type -> DeleteCategoryRequest
	2,  // 21: Good.UpdateCategory:input_type -> CategoryInfoRequest
	14, // 22: Good.BrandList:input_type -> BrandFilterRequest
	15, // 23: Good.CreateBrand:input_type -> BrandRequest
	15, // 24: Good.DeleteBrand:input_type -> BrandRequest
	15, // 25: Good.UpdateBrand:input_type -> BrandRequest
	0,  // 26: Good.BannerList:input_type -> Empty
	12, // 27: Good.CreateBanner:input_type -> BannerRequest
	12, // 28: Good.DeleteBanner:input_type -> BannerRequest
	12, // 29: Good.UpdateBanner:input_type -> BannerRequest
	8,  // 30: Good.CategoryBrandList:input_type -> CategoryBrandFilterRequest
	2,  // 31: Good.GetCategoryBrandList:input_type -> CategoryInfoRequest
	10, // 32: Good.CreateCategoryBrand:input_type -> CategoryBrandRequest
	10, // 33: Good.DeleteCategoryBrand:input_type -> CategoryBrandRequest
	10, // 34: Good.UpdateCategoryBrand:input_type -> CategoryBrandRequest
	30, // 35: Good.GoodList:output_type -> GoodListResponse
	30, // 36: Good.BatchGetGood:output_type -> GoodListResponse
	29, // 37: Good.CreateGood:output_type -> GoodInfoResponse
	0,  // 38: Good.DeleteGood:output_type -> Empty
	0,  // 39: Good.UpdateGood:output_type -> Empty
	29, // 40: Good.GetGoodDetail:output_type -> GoodInfoResponse
	6,  // 41: Good.GetAllCategorysList:output_type -> CategoryListResponse
	7,  // 42: Good.GetSubCategory:output_type -> SubCategoryListResponse
	5,  // 43: Good.CreateCategory:output_type -> CategoryInfoResponse
	0,  // 44: Good.DeleteCategory:output_type -> Empty
	0,  // 45: Good.UpdateCategory:output_type -> Empty
	17, // 46: Good.BrandList:output_type -> BrandListResponse
	16, // 47: Good.CreateBrand:output_type -> BrandInfoResponse
	0,  // 48: Good.DeleteBrand:output_type -> Empty
	0,  // 49: Good.UpdateBrand:output_type -> Empty
	18, // 50: Good.BannerList:output_type -> BannerListResponse
	13, // 51: Good.CreateBanner:output_type -> BannerResponse
	0,  // 52: Good.DeleteBanner:output_type -> Empty
	0,  // 53: Good.UpdateBanner:output_type -> Empty
	19, // 54: Good.CategoryBrandList:output_type -> CategoryBrandListResponse
	17, // 55: Good.GetCategoryBrandList:output_type -> BrandListResponse
	11, // 56: Good.CreateCategoryBrand:output_type -> CategoryBrandResponse
	0,  // 57: Good.DeleteCategoryBrand:output_type -> Empty
	0,  // 58: Good.UpdateCategoryBrand:output_type -> Empty
	35, // [35:59] is the sub-list for method output_type
	11, // [11:35] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_good_proto_init() }
func file_good_proto_init() {
	if File_good_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_good_proto_rawDesc), len(file_good_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_good_proto_goTypes,
		DependencyIndexes: file_good_proto_depIdxs,
		MessageInfos:      file_good_proto_msgTypes,
	}.Build()
	File_good_proto = out.File
	file_good_proto_goTypes = nil
	file_good_proto_depIdxs = nil
}
