// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: inventory.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GoodsInvInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsId       int32                  `protobuf:"varint,1,opt,name=goodsId,proto3" json:"goodsId,omitempty"` // 商品ID
	Stocks        int32                  `protobuf:"varint,2,opt,name=stocks,proto3" json:"stocks,omitempty"`   // 库存数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsInvInfo) Reset() {
	*x = GoodsInvInfo{}
	mi := &file_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsInvInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInvInfo) ProtoMessage() {}

func (x *GoodsInvInfo) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInvInfo.ProtoReflect.Descriptor instead.
func (*GoodsInvInfo) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *GoodsInvInfo) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *GoodsInvInfo) GetStocks() int32 {
	if x != nil {
		return x.Stocks
	}
	return 0
}

type OrderStockDetail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: Marked as deprecated in inventory.proto.
	LegacyOrderSn int32               `protobuf:"varint,1,opt,name=legacyOrderSn,proto3" json:"legacyOrderSn,omitempty"` // 旧版数字订单号，仅保留线协议兼容
	OrderGoods    []*OrderGoodsDetail `protobuf:"bytes,2,rep,name=orderGoods,proto3" json:"orderGoods,omitempty"`        // 订单商品明细
	OrderSn       string              `protobuf:"bytes,3,opt,name=orderSn,proto3" json:"orderSn,omitempty"`              // 当前字符串订单号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderStockDetail) Reset() {
	*x = OrderStockDetail{}
	mi := &file_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStockDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStockDetail) ProtoMessage() {}

func (x *OrderStockDetail) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStockDetail.ProtoReflect.Descriptor instead.
func (*OrderStockDetail) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{1}
}

// Deprecated: Marked as deprecated in inventory.proto.
func (x *OrderStockDetail) GetLegacyOrderSn() int32 {
	if x != nil {
		return x.LegacyOrderSn
	}
	return 0
}

func (x *OrderStockDetail) GetOrderGoods() []*OrderGoodsDetail {
	if x != nil {
		return x.OrderGoods
	}
	return nil
}

func (x *OrderStockDetail) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

type OrderGoodsDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsId       int32                  `protobuf:"varint,1,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	Num           int32                  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"` // 购买数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderGoodsDetail) Reset() {
	*x = OrderGoodsDetail{}
	mi := &file_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderGoodsDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderGoodsDetail) ProtoMessage() {}

func (x *OrderGoodsDetail) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderGoodsDetail.ProtoReflect.Descriptor instead.
func (*OrderGoodsDetail) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *OrderGoodsDetail) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *OrderGoodsDetail) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type ShowInvDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pages         int32                  `protobuf:"varint,1,opt,name=pages,proto3" json:"pages,omitempty"`
	PagePerNums   int32                  `protobuf:"varint,2,opt,name=pagePerNums,proto3" json:"pagePerNums,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowInvDetailRequest) Reset() {
	*x = ShowInvDetailRequest{}
	mi := &file_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowInvDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowInvDetailRequest) ProtoMessage() {}

func (x *ShowInvDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowInvDetailRequest.ProtoReflect.Descriptor instead.
func (*ShowInvDetailRequest) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *ShowInvDetailRequest) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *ShowInvDetailRequest) GetPagePerNums() int32 {
	if x != nil {
		return x.PagePerNums
	}
	return 0
}

type ShowInvDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data          []*GoodsInvInfo        `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowInvDetailResponse) Reset() {
	*x = ShowInvDetailResponse{}
	mi := &file_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowInvDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowInvDetailResponse) ProtoMessage() {}

func (x *ShowInvDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowInvDetailResponse.ProtoReflect.Descriptor instead.
func (*ShowInvDetailResponse) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *ShowInvDetailResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ShowInvDetailResponse) GetData() []*GoodsInvInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_inventory_proto protoreflect.FileDescriptor

const file_inventory_proto_rawDesc = "" +
	"\n" +
	"\x0finventory.proto\x1a\x1bgoogle/protobuf/empty.proto\"@\n" +
	"\fGoodsInvInfo\x12\x18\n" +
	"\agoodsId\x18\x01 \x01(\x05R\agoodsId\x12\x16\n" +
	"\x06stocks\x18\x02 \x01(\x05R\x06stocks\"\x89\x01\n" +
	"\x10OrderStockDetail\x12(\n" +
	"\rlegacyOrderSn\x18\x01 \x01(\x05B\x02\x18\x01R\rlegacyOrderSn\x121\n" +
	"\n" +
	"orderGoods\x18\x02 \x03(\v2\x11.OrderGoodsDetailR\n" +
	"orderGoods\x12\x18\n" +
	"\aorderSn\x18\x03 \x01(\tR\aorderSn\">\n" +
	"\x10OrderGoodsDetail\x12\x18\n" +
	"\agoodsId\x18\x01 \x01(\x05R\agoodsId\x12\x10\n" +
	"\x03num\x18\x02 \x01(\x05R\x03num\"N\n" +
	"\x14ShowInvDetailRequest\x12\x14\n" +
	"\x05pages\x18\x01 \x01(\x05R\x05pages\x12 \n" +
	"\vpagePerNums\x18\x02 \x01(\x05R\vpagePerNums\"P\n" +
	"\x15ShowInvDetailResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12!\n" +
	"\x04data\x18\x02 \x03(\v2\r.GoodsInvInfoR\x04data2\xa3\x02\n" +
	"\tInventory\x12/\n" +
	"\x06SetInv\x12\r.GoodsInvInfo\x1a\x16.google.protobuf.Empty\x12,\n" +
	"\fGetInvDetail\x12\r.GoodsInvInfo\x1a\r.GoodsInvInfo\x12<\n" +
	"\x0fStockSellDetail\x12\x11.OrderStockDetail\x1a\x16.google.protobuf.Empty\x129\n" +
	"\fRebackDetail\x12\x11.OrderStockDetail\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\rShowInvDetail\x12\x15.ShowInvDetailRequest\x1a\x16.ShowInvDetailResponseB\tZ\a.;protob\x06proto3"

var (
	file_inventory_proto_rawDescOnce sync.Once
	file_inventory_proto_rawDescData []byte
)

func file_inventory_proto_rawDescGZIP() []byte {
	file_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_proto_rawDesc), len(file_inventory_proto_rawDesc)))
	})
	return file_inventory_proto_rawDescData
}

var file_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_inventory_proto_goTypes = []any{
	(*GoodsInvInfo)(nil),          // 0: GoodsInvInfo
	(*OrderStockDetail)(nil),      // 1: OrderStockDetail
	(*OrderGoodsDetail)(nil),      // 2: OrderGoodsDetail
	(*ShowInvDetailRequest)(nil),  // 3: ShowInvDetailRequest
	(*ShowInvDetailResponse)(nil), // 4: ShowInvDetailResponse
	(*emptypb.Empty)(nil),         // 5: google.protobuf.Empty
}
var file_inventory_proto_depIdxs = []int32{
	2, // 0: OrderStockDetail.orderGoods:type_name -> OrderGoodsDetail
	0, // 1: ShowInvDetailResponse.data:type_name -> GoodsInvInfo
	0, // 2: Inventory.SetInv:input_type -> GoodsInvInfo
	0, // 3: Inventory.GetInvDetail:input_type -> GoodsInvInfo
	1, // 4: Inventory.StockSellDetail:input_type -> OrderStockDetail
	1, // 5: Inventory.RebackDetail:input_type -> OrderStockDetail
	3, // 6: Inventory.ShowInvDetail:input_type -> ShowInvDetailRequest
	5, // 7: Inventory.SetInv:output_type -> google.protobuf.Empty
	0, // 8: Inventory.GetInvDetail:output_type -> GoodsInvInfo
	5, // 9: Inventory.StockSellDetail:output_type -> google.protobuf.Empty
	5, // 10: Inventory.RebackDetail:output_type -> google.protobuf.Empty
	4, // 11: Inventory.ShowInvDetail:output_type -> ShowInvDetailResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_inventory_proto_init() }
func file_inventory_proto_init() {
	if File_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_proto_rawDesc), len(file_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_proto_depIdxs,
		MessageInfos:      file_inventory_proto_msgTypes,
	}.Build()
	File_inventory_proto = out.File
	file_inventory_proto_goTypes = nil
	file_inventory_proto_depIdxs = nil
}
