// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: order.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 订单请求：复用于创建与查询。
// 创建订单时填 userId + 收货信息（商品来自购物车已选项，id 留空）；
// 查询详情时填 id（+可选 userId 校验归属）。
type OrderInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`            // 订单ID（创建时为空；查询/更新时必填）
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`    // 用户ID（查询详情时 >0 用于校验归属）
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`   // 收货地址
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`         // 收货人
	Mobile        string                 `protobuf:"bytes,5,opt,name=mobile,proto3" json:"mobile,omitempty"`     // 联系电话
	Post          string                 `protobuf:"bytes,6,opt,name=post,proto3" json:"post,omitempty"`         // 留言
	PayType       int32                  `protobuf:"varint,7,opt,name=payType,proto3" json:"payType,omitempty"`  // 支付方式：1-微信 2-支付宝
	PostFee       float32                `protobuf:"fixed32,8,opt,name=postFee,proto3" json:"postFee,omitempty"` // 运费
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfoRequest) Reset() {
	*x = OrderInfoRequest{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfoRequest) ProtoMessage() {}

func (x *OrderInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfoRequest.ProtoReflect.Descriptor instead.
func (*OrderInfoRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *OrderInfoRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderInfoRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderInfoRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *OrderInfoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderInfoRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *OrderInfoRequest) GetPost() string {
	if x != nil {
		return x.Post
	}
	return ""
}

func (x *OrderInfoRequest) GetPayType() int32 {
	if x != nil {
		return x.PayType
	}
	return 0
}

func (x *OrderInfoRequest) GetPostFee() float32 {
	if x != nil {
		return x.PostFee
	}
	return 0
}

type OrderItemInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       int32                  `protobuf:"varint,2,opt,name=orderId,proto3" json:"orderId,omitempty"`
	GoodsId       int32                  `protobuf:"varint,3,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	GoodsName     string                 `protobuf:"bytes,4,opt,name=goodsName,proto3" json:"goodsName,omitempty"`
	GoodsImage    string                 `protobuf:"bytes,5,opt,name=goodsImage,proto3" json:"goodsImage,omitempty"`
	GoodsPrice    float32                `protobuf:"fixed32,6,opt,name=goodsPrice,proto3" json:"goodsPrice,omitempty"`
	Num           int32                  `protobuf:"varint,7,opt,name=num,proto3" json:"num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemInfoResponse) Reset() {
	*x = OrderItemInfoResponse{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemInfoResponse) ProtoMessage() {}

func (x *OrderItemInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemInfoResponse.ProtoReflect.Descriptor instead.
func (*OrderItemInfoResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *OrderItemInfoResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderItemInfoResponse) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderItemInfoResponse) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *OrderItemInfoResponse) GetGoodsName() string {
	if x != nil {
		return x.GoodsName
	}
	return ""
}

func (x *OrderItemInfoResponse) GetGoodsImage() string {
	if x != nil {
		return x.GoodsImage
	}
	return ""
}

func (x *OrderItemInfoResponse) GetGoodsPrice() float32 {
	if x != nil {
		return x.GoodsPrice
	}
	return 0
}

func (x *OrderItemInfoResponse) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type OrderInfoResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Id            int32                    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderSn       string                   `protobuf:"bytes,2,opt,name=orderSn,proto3" json:"orderSn,omitempty"` // 订单号
	UserId        int32                    `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	Address       string                   `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Name          string                   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Mobile        string                   `protobuf:"bytes,6,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Post          string                   `protobuf:"bytes,7,opt,name=post,proto3" json:"post,omitempty"`
	Status        int32                    `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"` // 订单状态：1-待支付 2-已支付 3-已取消/超时关闭 4-交易创建 5-交易结束
	PayType       int32                    `protobuf:"varint,9,opt,name=payType,proto3" json:"payType,omitempty"`
	Total         float32                  `protobuf:"fixed32,10,opt,name=total,proto3" json:"total,omitempty"`     // 商品总金额（不含运费）
	PostFee       float32                  `protobuf:"fixed32,11,opt,name=postFee,proto3" json:"postFee,omitempty"` // 运费
	AddTime       int64                    `protobuf:"varint,12,opt,name=addTime,proto3" json:"addTime,omitempty"`
	OrderGoods    []*OrderItemInfoResponse `protobuf:"bytes,13,rep,name=orderGoods,proto3" json:"orderGoods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfoResponse) Reset() {
	*x = OrderInfoResponse{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfoResponse) ProtoMessage() {}

func (x *OrderInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfoResponse.ProtoReflect.Descriptor instead.
func (*OrderInfoResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *OrderInfoResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderInfoResponse) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *OrderInfoResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderInfoResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *OrderInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderInfoResponse) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *OrderInfoResponse) GetPost() string {
	if x != nil {
		return x.Post
	}
	return ""
}

func (x *OrderInfoResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OrderInfoResponse) GetPayType() int32 {
	if x != nil {
		return x.PayType
	}
	return 0
}

func (x *OrderInfoResponse) GetTotal() float32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *OrderInfoResponse) GetPostFee() float32 {
	if x != nil {
		return x.PostFee
	}
	return 0
}

func (x *OrderInfoResponse) GetAddTime() int64 {
	if x != nil {
		return x.AddTime
	}
	return 0
}

func (x *OrderInfoResponse) GetOrderGoods() []*OrderItemInfoResponse {
	if x != nil {
		return x.OrderGoods
	}
	return nil
}

type DeleteOrderInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrderInfo) Reset() {
	*x = DeleteOrderInfo{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrderInfo) ProtoMessage() {}

func (x *DeleteOrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrderInfo.ProtoReflect.Descriptor instead.
func (*DeleteOrderInfo) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteOrderInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateOrderStatusInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderSn       string                 `protobuf:"bytes,1,opt,name=orderSn,proto3" json:"orderSn,omitempty"` // 订单号
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`  // 目标状态：1-待支付 2-已支付 3-已取消
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderStatusInfo) Reset() {
	*x = UpdateOrderStatusInfo{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderStatusInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderStatusInfo) ProtoMessage() {}

func (x *UpdateOrderStatusInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderStatusInfo.ProtoReflect.Descriptor instead.
func (*UpdateOrderStatusInfo) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateOrderStatusInfo) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *UpdateOrderStatusInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type OrderFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"` // 按用户过滤（0 不过滤）
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"` // 按状态过滤（0 不过滤）
	Pages         int32                  `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	PagePerNums   int32                  `protobuf:"varint,4,opt,name=pagePerNums,proto3" json:"pagePerNums,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderFilterRequest) Reset() {
	*x = OrderFilterRequest{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderFilterRequest) ProtoMessage() {}

func (x *OrderFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderFilterRequest.ProtoReflect.Descriptor instead.
func (*OrderFilterRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *OrderFilterRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderFilterRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OrderFilterRequest) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *OrderFilterRequest) GetPagePerNums() int32 {
	if x != nil {
		return x.PagePerNums
	}
	return 0
}

type OrderListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data          []*OrderInfoResponse   `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderListResponse) Reset() {
	*x = OrderListResponse{}
	mi := &file_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListResponse) ProtoMessage() {}

func (x *OrderListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListResponse.ProtoReflect.Descriptor instead.
func (*OrderListResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

func (x *OrderListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *OrderListResponse) GetData() []*OrderInfoResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

// 购物车
type CartItemListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"` // 用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItemListRequest) Reset() {
	*x = CartItemListRequest{}
	mi := &file_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItemListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItemListRequest) ProtoMessage() {}

func (x *CartItemListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItemListRequest.ProtoReflect.Descriptor instead.
func (*CartItemListRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{7}
}

func (x *CartItemListRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AddCartItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`   // 用户ID
	GoodsId       int32                  `protobuf:"varint,2,opt,name=goodsId,proto3" json:"goodsId,omitempty"` // 商品ID
	Num           int32                  `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`         // 添加数量
	Checked       bool                   `protobuf:"varint,4,opt,name=checked,proto3" json:"checked,omitempty"` // 是否选中
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCartItemRequest) Reset() {
	*x = AddCartItemRequest{}
	mi := &file_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCartItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCartItemRequest) ProtoMessage() {}

func (x *AddCartItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCartItemRequest.ProtoReflect.Descriptor instead.
func (*AddCartItemRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8}
}

func (x *AddCartItemRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddCartItemRequest) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *AddCartItemRequest) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *AddCartItemRequest) GetChecked() bool {
	if x != nil {
		return x.Checked
	}
	return false
}

type UpdateCartItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`           // 购物车记录ID
	Num           int32                  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`         // 新数量
	Checked       bool                   `protobuf:"varint,3,opt,name=checked,proto3" json:"checked,omitempty"` // 是否选中
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCartItemRequest) Reset() {
	*x = UpdateCartItemRequest{}
	mi := &file_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCartItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCartItemRequest) ProtoMessage() {}

func (x *UpdateCartItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCartItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateCartItemRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateCartItemRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCartItemRequest) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *UpdateCartItemRequest) GetChecked() bool {
	if x != nil {
		return x.Checked
	}
	return false
}

type DeleteCartItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 购物车记录ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCartItemRequest) Reset() {
	*x = DeleteCartItemRequest{}
	mi := &file_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCartItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCartItemRequest) ProtoMessage() {}

func (x *DeleteCartItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCartItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteCartItemRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteCartItemRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CartItemInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	GoodsId       int32                  `protobuf:"varint,3,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	Num           int32                  `protobuf:"varint,4,opt,name=num,proto3" json:"num,omitempty"`         // 购买数量
	Checked       bool                   `protobuf:"varint,5,opt,name=checked,proto3" json:"checked,omitempty"` // 是否选中
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItemInfoResponse) Reset() {
	*x = CartItemInfoResponse{}
	mi := &file_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItemInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItemInfoResponse) ProtoMessage() {}

func (x *CartItemInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItemInfoResponse.ProtoReflect.Descriptor instead.
func (*CartItemInfoResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{11}
}

func (x *CartItemInfoResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CartItemInfoResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CartItemInfoResponse) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *CartItemInfoResponse) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *CartItemInfoResponse) GetChecked() bool {
	if x != nil {
		return x.Checked
	}
	return false
}

type CartItemListResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Total         int32                   `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data          []*CartItemInfoResponse `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItemListResponse) Reset() {
	*x = CartItemListResponse{}
	mi := &file_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItemListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItemListResponse) ProtoMessage() {}

func (x *CartItemListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItemListResponse.ProtoReflect.Descriptor instead.
func (*CartItemListResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{12}
}

func (x *CartItemListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CartItemListResponse) GetData() []*CartItemInfoResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xc8\x01\n" +
	"\x10OrderInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x16\n" +
	"\x06mobile\x18\x05 \x01(\tR\x06mobile\x12\x12\n" +
	"\x04post\x18\x06 \x01(\tR\x04post\x12\x18\n" +
	"\apayType\x18\a \x01(\x05R\apayType\x12\x18\n" +
	"\apostFee\x18\b \x01(\x02R\apostFee\"\xcb\x01\n" +
	"\x15OrderItemInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\aorderId\x18\x02 \x01(\x05R\aorderId\x12\x18\n" +
	"\agoodsId\x18\x03 \x01(\x05R\agoodsId\x12\x1c\n" +
	"\tgoodsName\x18\x04 \x01(\tR\tgoodsName\x12\x1e\n" +
	"\n" +
	"goodsImage\x18\x05 \x01(\tR\n" +
	"goodsImage\x12\x1e\n" +
	"\n" +
	"goodsPrice\x18\x06 \x01(\x02R\n" +
	"goodsPrice\x12\x10\n" +
	"\x03num\x18\a \x01(\x05R\x03num\"\xe3\x02\n" +
	"\x11OrderInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\aorderSn\x18\x02 \x01(\tR\aorderSn\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\x05R\x06userId\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x16\n" +
	"\x06mobile\x18\x06 \x01(\tR\x06mobile\x12\x12\n" +
	"\x04post\x18\a \x01(\tR\x04post\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12\x18\n" +
	"\apayType\x18\t \x01(\x05R\apayType\x12\x14\n" +
	"\x05total\x18\n" +
	" \x01(\x02R\x05total\x12\x18\n" +
	"\apostFee\x18\v \x01(\x02R\apostFee\x12\x18\n" +
	"\aaddTime\x18\f \x01(\x03R\aaddTime\x126\n" +
	"\n" +
	"orderGoods\x18\r \x03(\v2\x16.OrderItemInfoResponseR\n" +
	"orderGoods\"!\n" +
	"\x0fDeleteOrderInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"I\n" +
	"\x15UpdateOrderStatusInfo\x12\x18\n" +
	"\aorderSn\x18\x01 \x01(\tR\aorderSn\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"|\n" +
	"\x12OrderFilterRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x14\n" +
	"\x05pages\x18\x03 \x01(\x05R\x05pages\x12 \n" +
	"\vpagePerNums\x18\x04 \x01(\x05R\vpagePerNums\"Q\n" +
	"\x11OrderListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12&\n" +
	"\x04data\x18\x02 \x03(\v2\x12.OrderInfoResponseR\x04data\"-\n" +
	"\x13CartItemListRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\"r\n" +
	"\x12AddCartItemRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\x12\x18\n" +
	"\agoodsId\x18\x02 \x01(\x05R\agoodsId\x12\x10\n" +
	"\x03num\x18\x03 \x01(\x05R\x03num\x12\x18\n" +
	"\achecked\x18\x04 \x01(\bR\achecked\"S\n" +
	"\x15UpdateCartItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x10\n" +
	"\x03num\x18\x02 \x01(\x05R\x03num\x12\x18\n" +
	"\achecked\x18\x03 \x01(\bR\achecked\"'\n" +
	"\x15DeleteCartItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x84\x01\n" +
	"\x14CartItemInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\x12\x18\n" +
	"\agoodsId\x18\x03 \x01(\x05R\agoodsId\x12\x10\n" +
	"\x03num\x18\x04 \x01(\x05R\x03num\x12\x18\n" +
	"\achecked\x18\x05 \x01(\bR\achecked\"W\n" +
	"\x14CartItemListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12)\n" +
	"\x04data\x18\x02 \x03(\v2\x15.CartItemInfoResponseR\x04data2\xa7\x04\n" +
	"\x05Order\x124\n" +
	"\vCreateOrder\x12\x11.OrderInfoRequest\x1a\x12.OrderInfoResponse\x124\n" +
	"\tOrderList\x12\x13.OrderFilterRequest\x1a\x12.OrderListResponse\x127\n" +
	"\x0eGetOrderDetail\x12\x11.OrderInfoRequest\x1a\x12.OrderInfoResponse\x12C\n" +
	"\x11UpdateOrderStatus\x12\x16.UpdateOrderStatusInfo\x1a\x16.google.protobuf.Empty\x127\n" +
	"\vDeleteOrder\x12\x10.DeleteOrderInfo\x1a\x16.google.protobuf.Empty\x12;\n" +
	"\fCartItemList\x12\x14.CartItemListRequest\x1a\x15.CartItemListResponse\x12:\n" +
	"\vAddCartItem\x12\x13.AddCartItemRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\x0eUpdateCartItem\x12\x16.UpdateCartItemRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\x0eDeleteCartItem\x12\x16.DeleteCartItemRequest\x1a\x16.google.protobuf.EmptyB\tZ\a.;protob\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_order_proto_goTypes = []any{
	(*OrderInfoRequest)(nil),      // 0: OrderInfoRequest
	(*OrderItemInfoResponse)(nil), // 1: OrderItemInfoResponse
	(*OrderInfoResponse)(nil),     // 2: OrderInfoResponse
	(*DeleteOrderInfo)(nil),       // 3: DeleteOrderInfo
	(*UpdateOrderStatusInfo)(nil), // 4: UpdateOrderStatusInfo
	(*OrderFilterRequest)(nil),    // 5: OrderFilterRequest
	(*OrderListResponse)(nil),     // 6: OrderListResponse
	(*CartItemListRequest)(nil),   // 7: CartItemListRequest
	(*AddCartItemRequest)(nil),    // 8: AddCartItemRequest
	(*UpdateCartItemRequest)(nil), // 9: UpdateCartItemRequest
	(*DeleteCartItemRequest)(nil), // 10: DeleteCartItemRequest
	(*CartItemInfoResponse)(nil),  // 11: CartItemInfoResponse
	(*CartItemListResponse)(nil),  // 12: CartItemListResponse
	(*emptypb.Empty)(nil),         // 13: google.protobuf.Empty
}
var file_order_proto_depIdxs = []int32{
	1,  // 0: OrderInfoResponse.orderGoods:type_name -> OrderItemInfoResponse
	2,  // 1: OrderListResponse.data:type_name -> OrderInfoResponse
	11, // 2: CartItemListResponse.data:type_name -> CartItemInfoResponse
	0,  // 3: Order.CreateOrder:input_type -> OrderInfoRequest
	5,  // 4: Order.OrderList:input_type -> OrderFilterRequest
	0,  // 5: Order.GetOrderDetail:input_type -> OrderInfoRequest
	4,  // 6: Order.UpdateOrderStatus:input_type -> UpdateOrderStatusInfo
	3,  // 7: Order.DeleteOrder:input_type -> DeleteOrderInfo
	7,  // 8: Order.CartItemList:input_type -> CartItemListRequest
	8,  // 9: Order.AddCartItem:input_type -> AddCartItemRequest
	9,  // 10: Order.UpdateCartItem:input_type -> UpdateCartItemRequest
	10, // 11: Order.DeleteCartItem:input_type -> DeleteCartItemRequest
	2,  // 12: Order.CreateOrder:output_type -> OrderInfoResponse
	6,  // 13: Order.OrderList:output_type -> OrderListResponse
	2,  // 14: Order.GetOrderDetail:output_type -> OrderInfoResponse
	13, // 15: Order.UpdateOrderStatus:output_type -> google.protobuf.Empty
	13, // 16: Order.DeleteOrder:output_type -> google.protobuf.Empty
	12, // 17: Order.CartItemList:output_type -> CartItemListResponse
	13, // 18: Order.AddCartItem:output_type -> google.protobuf.Empty
	13, // 19: Order.UpdateCartItem:output_type -> google.protobuf.Empty
	13, // 20: Order.DeleteCartItem:output_type -> google.protobuf.Empty
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
