// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: userop.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserFavListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFavListRequest) Reset() {
	*x = UserFavListRequest{}
	mi := &file_userop_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFavListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFavListRequest) ProtoMessage() {}

func (x *UserFavListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userop_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFavListRequest.ProtoReflect.Descriptor instead.
func (*UserFavListRequest) Descriptor() ([]byte, []int) {
	return file_userop_proto_rawDescGZIP(), []int{0}
}

func (x *UserFavListRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UserFavRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	GoodsId       int32                  `protobuf:"varint,2,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFavRequest) Reset() {
	*x = UserFavRequest{}
	mi := &file_userop_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFavRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFavRequest) ProtoMessage() {}

func (x *UserFavRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userop_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFavRequest.ProtoReflect.Descriptor instead.
func (*UserFavRequest) Descriptor() ([]byte, []int) {
	return file_userop_proto_rawDescGZIP(), []int{1}
}

func (x *UserFavRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserFavRequest) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

type UserFavInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	GoodsId       int32                  `protobuf:"varint,3,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFavInfoResponse) Reset() {
	*x = UserFavInfoResponse{}
	mi := &file_userop_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFavInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFavInfoResponse) ProtoMessage() {}

func (x *UserFavInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userop_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFavInfoResponse.ProtoReflect.Descriptor instead.
func (*UserFavInfoResponse) Descriptor() ([]byte, []int) {
	return file_userop_proto_rawDescGZIP(), []int{2}
}

func (x *UserFavInfoResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserFavInfoResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserFavInfoResponse) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

type UserFavListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data          []*UserFavInfoResponse `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFavListResponse) Reset() {
	*x = UserFavListResponse{}
	mi := &file_userop_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFavListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFavListResponse) ProtoMessage() {}

func (x *UserFavListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userop_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFavListResponse.ProtoReflect.Descriptor instead.
func (*UserFavListResponse) Descriptor() ([]byte, []int) {
	return file_userop_proto_rawDescGZIP(), []int{3}
}

func (x *UserFavListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *UserFavListResponse) GetData() []*UserFavInfoResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type AddressListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressListRequest) Reset() {
	*x = AddressListRequest{}
	mi := &file_userop_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressListRequest) ProtoMessage() {}

func (x *AddressListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userop_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressListRequest.ProtoReflect.Descriptor instead.
func (*AddressListRequest) Descriptor() ([]byte, []int) {
	return file_userop_proto_rawDescGZIP(), []int{4}
}

func (x *AddressListRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Province      string                 `protobuf:"bytes,3,opt,name=province,proto3" json:"province,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	District      string                 `protobuf:"bytes,5,opt,name=district,proto3" json:"district,omitempty"`
	Address       string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	SignerName    string                 `protobuf:"bytes,7,opt,name=signerName,proto3" json:"signerName,omitempty"`
	SignerMobile  string                 `protobuf:"bytes,8,opt,name=signerMobile,proto3" json:"signerMobile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressRequest) Reset() {
	*x = AddressRequest{}
	mi := &file_userop_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressRequest) ProtoMessage() {}

func (x *AddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userop_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressRequest.ProtoReflect.Descriptor instead.
func (*AddressRequest) Descriptor() ([]byte, []int) {
	return file_userop_proto_rawDescGZIP(), []int{5}
}

func (x *AddressRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddressRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddressRequest) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *AddressRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *AddressRequest) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *AddressRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AddressRequest) GetSignerName() string {
	if x != nil {
		return x.SignerName
	}
	return ""
}

func (x *AddressRequest) GetSignerMobile() string {
	if x != nil {
		return x.SignerMobile
	}
	return ""
}

type DeleteAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAddressRequest) Reset() {
	*x = DeleteAddressRequest{}
	mi := &file_userop_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAddressRequest) ProtoMessage() {}

func (x *DeleteAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userop_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAddressRequest.ProtoReflect.Descriptor instead.
func (*DeleteAddressRequest) Descriptor() ([]byte, []int) {
	return file_userop_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteAddressRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteAddressRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AddressInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Province      string                 `protobuf:"bytes,3,opt,name=province,proto3" json:"province,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	District      string                 `protobuf:"bytes,5,opt,name=district,proto3" json:"district,omitempty"`
	Address       string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	SignerName    string                 `protobuf:"bytes,7,opt,name=signerName,proto3" json:"signerName,omitempty"`
	SignerMobile  string                 `protobuf:"bytes,8,opt,name=signerMobile,proto3" json:"signerMobile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressInfoResponse) Reset() {
	*x = AddressInfoResponse{}
	mi := &file_userop_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressInfoResponse) ProtoMessage() {}

func (x *AddressInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userop_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressInfoResponse.ProtoReflect.Descriptor instead.
func (*AddressInfoResponse) Descriptor() ([]byte, []int) {
	return file_userop_proto_rawDescGZIP(), []int{7}
}

func (x *AddressInfoResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddressInfoResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddressInfoResponse) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *AddressInfoResponse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *AddressInfoResponse) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *AddressInfoResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AddressInfoResponse) GetSignerName() string {
	if x != nil {
		return x.SignerName
	}
	return ""
}

func (x *AddressInfoResponse) GetSignerMobile() string {
	if x != nil {
		return x.SignerMobile
	}
	return ""
}

type AddressListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data          []*AddressInfoResponse `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressListResponse) Reset() {
	*x = AddressListResponse{}
	mi := &file_userop_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressListResponse) ProtoMessage() {}

func (x *AddressListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userop_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressListResponse.ProtoReflect.Descriptor instead.
func (*AddressListResponse) Descriptor() ([]byte, []int) {
	return file_userop_proto_rawDescGZIP(), []int{8}
}

func (x *AddressListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *AddressListResponse) GetData() []*AddressInfoResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type MessageListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageListRequest) Reset() {
	*x = MessageListRequest{}
	mi := &file_userop_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageListRequest) ProtoMessage() {}

func (x *MessageListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userop_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageListRequest.ProtoReflect.Descriptor instead.
func (*MessageListRequest) Descriptor() ([]byte, []int) {
	return file_userop_proto_rawDescGZIP(), []int{9}
}

func (x *MessageListRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type MessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Type          int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	File          string                 `protobuf:"bytes,5,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageRequest) Reset() {
	*x = MessageRequest{}
	mi := &file_userop_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRequest) ProtoMessage() {}

func (x *MessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userop_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRequest.ProtoReflect.Descriptor instead.
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return file_userop_proto_rawDescGZIP(), []int{10}
}

func (x *MessageRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MessageRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *MessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MessageRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *MessageRequest) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

type DeleteMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageRequest) Reset() {
	*x = DeleteMessageRequest{}
	mi := &file_userop_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageRequest) ProtoMessage() {}

func (x *DeleteMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userop_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageRequest.ProtoReflect.Descriptor instead.
func (*DeleteMessageRequest) Descriptor() ([]byte, []int) {
	return file_userop_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteMessageRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteMessageRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MessageInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Type          int32                  `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	File          string                 `protobuf:"bytes,6,opt,name=file,proto3" json:"file,omitempty"`
	AddTime       int64                  `protobuf:"varint,7,opt,name=addTime,proto3" json:"addTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageInfoResponse) Reset() {
	*x = MessageInfoResponse{}
	mi := &file_userop_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageInfoResponse) ProtoMessage() {}

func (x *MessageInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userop_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageInfoResponse.ProtoReflect.Descriptor instead.
func (*MessageInfoResponse) Descriptor() ([]byte, []int) {
	return file_userop_proto_rawDescGZIP(), []int{12}
}

func (x *MessageInfoResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MessageInfoResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MessageInfoResponse) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *MessageInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MessageInfoResponse) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *MessageInfoResponse) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *MessageInfoResponse) GetAddTime() int64 {
	if x != nil {
		return x.AddTime
	}
	return 0
}

type MessageListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data          []*MessageInfoResponse `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageListResponse) Reset() {
	*x = MessageListResponse{}
	mi := &file_userop_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageListResponse) ProtoMessage() {}

func (x *MessageListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userop_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageListResponse.ProtoReflect.Descriptor instead.
func (*MessageListResponse) Descriptor() ([]byte, []int) {
	return file_userop_proto_rawDescGZIP(), []int{13}
}

func (x *MessageListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *MessageListResponse) GetData() []*MessageInfoResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_userop_proto protoreflect.FileDescriptor

const file_userop_proto_rawDesc = "" +
	"\n" +
	"\fuserop.proto\x1a\x1bgoogle/protobuf/empty.proto\",\n" +
	"\x12UserFavListRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\"B\n" +
	"\x0eUserFavRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\x12\x18\n" +
	"\agoodsId\x18\x02 \x01(\x05R\agoodsId\"W\n" +
	"\x13UserFavInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\x12\x18\n" +
	"\agoodsId\x18\x03 \x01(\x05R\agoodsId\"U\n" +
	"\x13UserFavListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12(\n" +
	"\x04data\x18\x02 \x03(\v2\x14.UserFavInfoResponseR\x04data\",\n" +
	"\x12AddressListRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\"\xe2\x01\n" +
	"\x0eAddressRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\x12\x1a\n" +
	"\bprovince\x18\x03 \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x1a\n" +
	"\bdistrict\x18\x05 \x01(\tR\bdistrict\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\x12\x1e\n" +
	"\n" +
	"signerName\x18\a \x01(\tR\n" +
	"signerName\x12\"\n" +
	"\fsignerMobile\x18\b \x01(\tR\fsignerMobile\">\n" +
	"\x14DeleteAddressRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\"\xe7\x01\n" +
	"\x13AddressInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\x12\x1a\n" +
	"\bprovince\x18\x03 \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x1a\n" +
	"\bdistrict\x18\x05 \x01(\tR\bdistrict\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\x12\x1e\n" +
	"\n" +
	"signerName\x18\a \x01(\tR\n" +
	"signerName\x12\"\n" +
	"\fsignerMobile\x18\b \x01(\tR\fsignerMobile\"U\n" +
	"\x13AddressListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12(\n" +
	"\x04data\x18\x02 \x03(\v2\x14.AddressInfoResponseR\x04data\",\n" +
	"\x12MessageListRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\"\x84\x01\n" +
	"\x0eMessageRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12\x12\n" +
	"\x04file\x18\x05 \x01(\tR\x04file\">\n" +
	"\x14DeleteMessageRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\"\xb3\x01\n" +
	"\x13MessageInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x12\n" +
	"\x04type\x18\x05 \x01(\x05R\x04type\x12\x12\n" +
	"\x04file\x18\x06 \x01(\tR\x04file\x12\x18\n" +
	"\aaddTime\x18\a \x01(\x03R\aaddTime\"U\n" +
	"\x13MessageListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12(\n" +
	"\x04data\x18\x02 \x03(\v2\x14.MessageInfoResponseR\x04data2\x90\x05\n" +
	"\x06UserOp\x12;\n" +
	"\x0eGetUserFavList\x12\x13.UserFavListRequest\x1a\x14.UserFavListResponse\x123\n" +
	"\n" +
	"GetUserFav\x12\x0f.UserFavRequest\x1a\x14.UserFavInfoResponse\x126\n" +
	"\rCreateUserFav\x12\x0f.UserFavRequest\x1a\x14.UserFavInfoResponse\x128\n" +
	"\rDeleteUserFav\x12\x0f.UserFavRequest\x1a\x16.google.protobuf.Empty\x12;\n" +
	"\x0eGetAddressList\x12\x13.AddressListRequest\x1a\x14.AddressListResponse\x126\n" +
	"\rCreateAddress\x12\x0f.AddressRequest\x1a\x14.AddressInfoResponse\x128\n" +
	"\rUpdateAddress\x12\x0f.AddressRequest\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\rDeleteAddress\x12\x15.DeleteAddressRequest\x1a\x16.google.protobuf.Empty\x12;\n" +
	"\x0eGetMessageList\x12\x13.MessageListRequest\x1a\x14.MessageListResponse\x126\n" +
	"\rCreateMessage\x12\x0f.MessageRequest\x1a\x14.MessageInfoResponse\x12>\n" +
	"\rDeleteMessage\x12\x15.DeleteMessageRequest\x1a\x16.google.protobuf.EmptyB\tZ\a.;protob\x06proto3"

var (
	file_userop_proto_rawDescOnce sync.Once
	file_userop_proto_rawDescData []byte
)

func file_userop_proto_rawDescGZIP() []byte {
	file_userop_proto_rawDescOnce.Do(func() {
		file_userop_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_userop_proto_rawDesc), len(file_userop_proto_rawDesc)))
	})
	return file_userop_proto_rawDescData
}

var file_userop_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_userop_proto_goTypes = []any{
	(*UserFavListRequest)(nil),   // 0: UserFavListRequest
	(*UserFavRequest)(nil),       // 1: UserFavRequest
	(*UserFavInfoResponse)(nil),  // 2: UserFavInfoResponse
	(*UserFavListResponse)(nil),  // 3: UserFavListResponse
	(*AddressListRequest)(nil),   // 4: AddressListRequest
	(*AddressRequest)(nil),       // 5: AddressRequest
	(*DeleteAddressRequest)(nil), // 6: DeleteAddressRequest
	(*AddressInfoResponse)(nil),  // 7: AddressInfoResponse
	(*AddressListResponse)(nil),  // 8: AddressListResponse
	(*MessageListRequest)(nil),   // 9: MessageListRequest
	(*MessageRequest)(nil),       // 10: MessageRequest
	(*DeleteMessageRequest)(nil), // 11: DeleteMessageRequest
	(*MessageInfoResponse)(nil),  // 12: MessageInfoResponse
	(*MessageListResponse)(nil),  // 13: MessageListResponse
	(*emptypb.Empty)(nil),        // 14: google.protobuf.Empty
}
var file_userop_proto_depIdxs = []int32{
	2,  // 0: UserFavListResponse.data:type_name -> UserFavInfoResponse
	7,  // 1: AddressListResponse.data:type_name -> AddressInfoResponse
	12, // 2: MessageListResponse.data:type_name -> MessageInfoResponse
	0,  // 3: UserOp.GetUserFavList:input_type -> UserFavListRequest
	1,  // 4: UserOp.GetUserFav:input_type -> UserFavRequest
	1,  // 5: UserOp.CreateUserFav:input_type -> UserFavRequest
	1,  // 6: UserOp.DeleteUserFav:input_type -> UserFavRequest
	4,  // 7: UserOp.GetAddressList:input_type -> AddressListRequest
	5,  // 8: UserOp.CreateAddress:input_type -> AddressRequest
	5,  // 9: UserOp.UpdateAddress:input_type -> AddressRequest
	6,  // 10: UserOp.DeleteAddress:input_type -> DeleteAddressRequest
	9,  // 11: UserOp.GetMessageList:input_type -> MessageListRequest
	10, // 12: UserOp.CreateMessage:input_type -> MessageRequest
	11, // 13: UserOp.DeleteMessage:input_type -> DeleteMessageRequest
	3,  // 14: UserOp.GetUserFavList:output_type -> UserFavListResponse
	2,  // 15: UserOp.GetUserFav:output_type -> UserFavInfoResponse
	2,  // 16: UserOp.CreateUserFav:output_type -> UserFavInfoResponse
	14, // 17: UserOp.DeleteUserFav:output_type -> google.protobuf.Empty
	8,  // 18: UserOp.GetAddressList:output_type -> AddressListResponse
	7,  // 19: UserOp.CreateAddress:output_type -> AddressInfoResponse
	14, // 20: UserOp.UpdateAddress:output_type -> google.protobuf.Empty
	14, // 21: UserOp.DeleteAddress:output_type -> google.protobuf.Empty
	13, // 22: UserOp.GetMessageList:output_type -> MessageListResponse
	12, // 23: UserOp.CreateMessage:output_type -> MessageInfoResponse
	14, // 24: UserOp.DeleteMessage:output_type -> google.protobuf.Empty
	14, // [14:25] is the sub-list for method output_type
	3,  // [3:14] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_userop_proto_init() }
func file_userop_proto_init() {
	if File_userop_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_userop_proto_rawDesc), len(file_userop_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_userop_proto_goTypes,
		DependencyIndexes: file_userop_proto_depIdxs,
		MessageInfos:      file_userop_proto_msgTypes,
	}.Build()
	File_userop_proto = out.File
	file_userop_proto_goTypes = nil
	file_userop_proto_depIdxs = nil
}
