// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: userop.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserOp_GetUserFavList_FullMethodName = "/UserOp/GetUserFavList"
	UserOp_GetUserFav_FullMethodName     = "/UserOp/GetUserFav"
	UserOp_CreateUserFav_FullMethodName  = "/UserOp/CreateUserFav"
	UserOp_DeleteUserFav_FullMethodName  = "/UserOp/DeleteUserFav"
	UserOp_GetAddressList_FullMethodName = "/UserOp/GetAddressList"
	UserOp_CreateAddress_FullMethodName  = "/UserOp/CreateAddress"
	UserOp_UpdateAddress_FullMethodName  = "/UserOp/UpdateAddress"
	UserOp_DeleteAddress_FullMethodName  = "/UserOp/DeleteAddress"
	UserOp_GetMessageList_FullMethodName = "/UserOp/GetMessageList"
	UserOp_CreateMessage_FullMethodName  = "/UserOp/CreateMessage"
	UserOp_DeleteMessage_FullMethodName  = "/UserOp/DeleteMessage"
)

// UserOpClient is the client API for UserOp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserOpClient interface {
	// 收藏
	GetUserFavList(ctx context.Context, in *UserFavListRequest, opts ...grpc.CallOption) (*UserFavListResponse, error)
	GetUserFav(ctx context.Context, in *UserFavRequest, opts ...grpc.CallOption) (*UserFavInfoResponse, error)
	CreateUserFav(ctx context.Context, in *UserFavRequest, opts ...grpc.CallOption) (*UserFavInfoResponse, error)
	DeleteUserFav(ctx context.Context, in *UserFavRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 收货地址
	GetAddressList(ctx context.Context, in *AddressListRequest, opts ...grpc.CallOption) (*AddressListResponse, error)
	CreateAddress(ctx context.Context, in *AddressRequest, opts ...grpc.CallOption) (*AddressInfoResponse, error)
	UpdateAddress(ctx context.Context, in *AddressRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteAddress(ctx context.Context, in *DeleteAddressRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 留言
	GetMessageList(ctx context.Context, in *MessageListRequest, opts ...grpc.CallOption) (*MessageListResponse, error)
	CreateMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageInfoResponse, error)
	DeleteMessage(ctx context.Context, in *DeleteMessageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type userOpClient struct {
	cc grpc.ClientConnInterface
}

func NewUserOpClient(cc grpc.ClientConnInterface) UserOpClient {
	return &userOpClient{cc}
}

func (c *userOpClient) GetUserFavList(ctx context.Context, in *UserFavListRequest, opts ...grpc.CallOption) (*UserFavListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserFavListResponse)
	err := c.cc.Invoke(ctx, UserOp_GetUserFavList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userOpClient) GetUserFav(ctx context.Context, in *UserFavRequest, opts ...grpc.CallOption) (*UserFavInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserFavInfoResponse)
	err := c.cc.Invoke(ctx, UserOp_GetUserFav_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userOpClient) CreateUserFav(ctx context.Context, in *UserFavRequest, opts ...grpc.CallOption) (*UserFavInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserFavInfoResponse)
	err := c.cc.Invoke(ctx, UserOp_CreateUserFav_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userOpClient) DeleteUserFav(ctx context.Context, in *UserFavRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UserOp_DeleteUserFav_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userOpClient) GetAddressList(ctx context.Context, in *AddressListRequest, opts ...grpc.CallOption) (*AddressListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddressListResponse)
	err := c.cc.Invoke(ctx, UserOp_GetAddressList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userOpClient) CreateAddress(ctx context.Context, in *AddressRequest, opts ...grpc.CallOption) (*AddressInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddressInfoResponse)
	err := c.cc.Invoke(ctx, UserOp_CreateAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userOpClient) UpdateAddress(ctx context.Context, in *AddressRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UserOp_UpdateAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userOpClient) DeleteAddress(ctx context.Context, in *DeleteAddressRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UserOp_DeleteAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userOpClient) GetMessageList(ctx context.Context, in *MessageListRequest, opts ...grpc.CallOption) (*MessageListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageListResponse)
	err := c.cc.Invoke(ctx, UserOp_GetMessageList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userOpClient) CreateMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageInfoResponse)
	err := c.cc.Invoke(ctx, UserOp_CreateMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userOpClient) DeleteMessage(ctx context.Context, in *DeleteMessageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UserOp_DeleteMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserOpServer is the server API for UserOp service.
// All implementations must embed UnimplementedUserOpServer
// for forward compatibility.
type UserOpServer interface {
	// 收藏
	GetUserFavList(context.Context, *UserFavListRequest) (*UserFavListResponse, error)
	GetUserFav(context.Context, *UserFavRequest) (*UserFavInfoResponse, error)
	CreateUserFav(context.Context, *UserFavRequest) (*UserFavInfoResponse, error)
	DeleteUserFav(context.Context, *UserFavRequest) (*emptypb.Empty, error)
	// 收货地址
	GetAddressList(context.Context, *AddressListRequest) (*AddressListResponse, error)
	CreateAddress(context.Context, *AddressRequest) (*AddressInfoResponse, error)
	UpdateAddress(context.Context, *AddressRequest) (*emptypb.Empty, error)
	DeleteAddress(context.Context, *DeleteAddressRequest) (*emptypb.Empty, error)
	// 留言
	GetMessageList(context.Context, *MessageListRequest) (*MessageListResponse, error)
	CreateMessage(context.Context, *MessageRequest) (*MessageInfoResponse, error)
	DeleteMessage(context.Context, *DeleteMessageRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedUserOpServer()
}

// UnimplementedUserOpServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserOpServer struct{}

func (UnimplementedUserOpServer) GetUserFavList(context.Context, *UserFavListRequest) (*UserFavListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserFavList not implemented")
}
func (UnimplementedUserOpServer) GetUserFav(context.Context, *UserFavRequest) (*UserFavInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserFav not implemented")
}
func (UnimplementedUserOpServer) CreateUserFav(context.Context, *UserFavRequest) (*UserFavInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUserFav not implemented")
}
func (UnimplementedUserOpServer) DeleteUserFav(context.Context, *UserFavRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUserFav not implemented")
}
func (UnimplementedUserOpServer) GetAddressList(context.Context, *AddressListRequest) (*AddressListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAddressList not implemented")
}
func (UnimplementedUserOpServer) CreateAddress(context.Context, *AddressRequest) (*AddressInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAddress not implemented")
}
func (UnimplementedUserOpServer) UpdateAddress(context.Context, *AddressRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAddress not implemented")
}
func (UnimplementedUserOpServer) DeleteAddress(context.Context, *DeleteAddressRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAddress not implemented")
}
func (UnimplementedUserOpServer) GetMessageList(context.Context, *MessageListRequest) (*MessageListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMessageList not implemented")
}
func (UnimplementedUserOpServer) CreateMessage(context.Context, *MessageRequest) (*MessageInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMessage not implemented")
}
func (UnimplementedUserOpServer) DeleteMessage(context.Context, *DeleteMessageRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMessage not implemented")
}
func (UnimplementedUserOpServer) mustEmbedUnimplementedUserOpServer() {}
func (UnimplementedUserOpServer) testEmbeddedByValue()                {}

// UnsafeUserOpServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserOpServer will
// result in compilation errors.
type UnsafeUserOpServer interface {
	mustEmbedUnimplementedUserOpServer()
}

func RegisterUserOpServer(s grpc.ServiceRegistrar, srv UserOpServer) {
	// If the following call panics, it indicates UnimplementedUserOpServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserOp_ServiceDesc, srv)
}

func _UserOp_GetUserFavList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserFavListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserOpServer).GetUserFavList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserOp_GetUserFavList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserOpServer).GetUserFavList(ctx, req.(*UserFavListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserOp_GetUserFav_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserFavRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserOpServer).GetUserFav(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserOp_GetUserFav_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserOpServer).GetUserFav(ctx, req.(*UserFavRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserOp_CreateUserFav_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserFavRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserOpServer).CreateUserFav(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserOp_CreateUserFav_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserOpServer).CreateUserFav(ctx, req.(*UserFavRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserOp_DeleteUserFav_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserFavRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserOpServer).DeleteUserFav(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserOp_DeleteUserFav_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserOpServer).DeleteUserFav(ctx, req.(*UserFavRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserOp_GetAddressList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserOpServer).GetAddressList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserOp_GetAddressList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserOpServer).GetAddressList(ctx, req.(*AddressListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserOp_CreateAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserOpServer).CreateAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserOp_CreateAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserOpServer).CreateAddress(ctx, req.(*AddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserOp_UpdateAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserOpServer).UpdateAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserOp_UpdateAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserOpServer).UpdateAddress(ctx, req.(*AddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserOp_DeleteAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserOpServer).DeleteAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserOp_DeleteAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserOpServer).DeleteAddress(ctx, req.(*DeleteAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserOp_GetMessageList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserOpServer).GetMessageList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserOp_GetMessageList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserOpServer).GetMessageList(ctx, req.(*MessageListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserOp_CreateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserOpServer).CreateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserOp_CreateMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserOpServer).CreateMessage(ctx, req.(*MessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserOp_DeleteMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserOpServer).DeleteMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserOp_DeleteMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserOpServer).DeleteMessage(ctx, req.(*DeleteMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserOp_ServiceDesc is the grpc.ServiceDesc for UserOp service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserOp_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "UserOp",
	HandlerType: (*UserOpServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserFavList",
			Handler:    _UserOp_GetUserFavList_Handler,
		},
		{
			MethodName: "GetUserFav",
			Handler:    _UserOp_GetUserFav_Handler,
		},
		{
			MethodName: "CreateUserFav",
			Handler:    _UserOp_CreateUserFav_Handler,
		},
		{
			MethodName: "DeleteUserFav",
			Handler:    _UserOp_DeleteUserFav_Handler,
		},
		{
			MethodName: "GetAddressList",
			Handler:    _UserOp_GetAddressList_Handler,
		},
		{
			MethodName: "CreateAddress",
			Handler:    _UserOp_CreateAddress_Handler,
		},
		{
			MethodName: "UpdateAddress",
			Handler:    _UserOp_UpdateAddress_Handler,
		},
		{
			MethodName: "DeleteAddress",
			Handler:    _UserOp_DeleteAddress_Handler,
		},
		{
			MethodName: "GetMessageList",
			Handler:    _UserOp_GetMessageList_Handler,
		},
		{
			MethodName: "CreateMessage",
			Handler:    _UserOp_CreateMessage_Handler,
		},
		{
			MethodName: "DeleteMessage",
			Handler:    _UserOp_DeleteMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "userop.proto",
}
