api:
  dashboard: true
  insecure: true

ping: {}

entryPoints:
  web:
    address: ":80"
  traefik:
    address: ":8080"

providers:
  consulCatalog:
    endpoint:
      address: "consul:8500"
      scheme: http
    exposedByDefault: false
    refreshInterval: "15s"

log:
  level: INFO

accessLog: {}
